//go:build unix

package compat

import (
	"fmt"
	"regexp"
	"strconv"
	"strings"
)

// BashSuiteDoc renders docs/bash-suite.md (#211): the scoreboard whose
// denominator is the incumbent's own spec rather than one we chose.
func BashSuiteDoc(results []SuiteResult, bashVersion, suiteVersion string) string {
	s := SummarizeSuite(results)
	var b strings.Builder

	b.WriteString("# bash's own test suite, run through koi\n\n")
	b.WriteString("*Generated by `make bash-suite` from `internal/compat` — do not edit by hand.*\n\n")
	fmt.Fprintf(&b, "Suite: **bash %s** `tests/`. Oracle: **%s** on the machine that ran this.\n\n",
		suiteVersion, bashVersion)

	b.WriteString("| measure | result | what it answers |\n| --- | --- | --- |\n")
	fmt.Fprintf(&b, "| **strict** | **%d/%d files (%d%%)** | identical output *and* exit status for a whole file |\n",
		s.Passed, s.Files, s.Rate())
	fmt.Fprintf(&b, "| parsed | %d/%d files (%d%%) | koi can read the file at all |\n",
		s.Parsed, s.Files, s.ParseRate())
	fmt.Fprintf(&b, "| line agreement | %d/%d lines (%d%%) | how much of bash's output koi reproduced exactly |\n\n",
		s.MatchedLine, s.BashLines, s.LineRate())

	b.WriteString(`**Quote the strict number.** It is the harshest of the three and the
one a skeptic should use: one wrong line anywhere in a 369-line file of
deliberate bash arcana fails the whole file. It is not comparable to the
` + "[curated corpus](compat.md)" + `, which asks a different and much easier
question — does the stuff people actually paste work — against a
denominator we chose ourselves.

The other two are here because a single number would mislead in both
directions. koi parses a script **up front**, so one unsupported
construct on line 129 forfeits the other 368 lines: the strict figure is
dominated by parse coverage rather than by runtime behavior, and
publishing it alone would hide where the gap actually is.

`)

	gaps := ParseGaps(results)
	if len(gaps) > 0 {
		b.WriteString("## What the parser cannot read\n\n")
		b.WriteString(`Each of these stops a whole file. They are the sharpest upstream targets
we have for [#119](https://github.com/blairham/koi-shell/issues/119),
because bash's own suite is the evidence that real bash code uses them.

`)
		b.WriteString("| construct | files |\n| --- | --- |\n")
		for _, g := range gaps {
			fmt.Fprintf(&b, "| %s | %s |\n", escapePipes(g.Message), strings.Join(g.Files, ", "))
		}
		b.WriteString("\n")
	}

	b.WriteString("## Files that pass strictly\n\n")
	var passed []string
	for _, r := range results {
		if r.Pass {
			passed = append(passed, "`"+r.File+"`")
		}
	}
	if len(passed) == 0 {
		b.WriteString("None yet.\n\n")
	} else {
		fmt.Fprintf(&b, "%s\n\n", strings.Join(passed, ", "))
	}

	b.WriteString(`## Why the suite is not in this repository

Every file in bash's ` + "`tests/`" + ` carries a GPLv3 header, and koi is MIT.
Vendoring them would relicense this repository by accident. So the suite
is **fetched, never committed**: ` + "`make bash-suite`" + ` downloads the tarball
into ` + "`build/`" + `, builds bash's own ` + "`recho`/`zecho`/`printenv`" + ` helpers from
` + "`support/*.c`" + `, and runs the comparison. Without those helpers both
shells print "command not found" for most assertions and the comparison
measures nothing. The first run of this scored 0/83 and none of it was
koi: the helpers were missing *and* the shell was being invoked by a path
that could not execute. Both faults look identical from the outside,
which is why the harness now asserts its own sanity rather than trusting
a zero.

## Why bash is the oracle rather than the shipped .right files

bash's own harness diffs against ` + "`.right`" + ` files generated by the version
that shipped them. Comparing koi against those would fold every
difference between the local bash and the tarball's bash into koi's
score. Instead each file runs through the *local* bash and through koi,
and the two are compared — the same discipline as
[docs/compat.md](compat.md), and the reason nothing here encodes what we
think bash ought to do.

## This is not a CI gate

It needs the network and a C compiler, so it is run on demand rather than
on every pull request. The number belongs in release notes — that is the
cadence the move depends on — not in a check that fails when GNU's FTP is
slow.
`)
	return b.String()
}

// SuiteDelta is the one line a release note carries: what moved since
// the last published run.
func SuiteDelta(prev, cur SuiteSummary) string {
	if prev.Files == 0 {
		return fmt.Sprintf("bash suite: %d%% strict, %d%% parsed, %d%% lines (first run)",
			cur.Rate(), cur.ParseRate(), cur.LineRate())
	}
	return fmt.Sprintf("bash suite: %d%% → %d%% strict, %d%% → %d%% parsed, %d%% → %d%% lines",
		prev.Rate(), cur.Rate(), prev.ParseRate(), cur.ParseRate(), prev.LineRate(), cur.LineRate())
}

// publishedRe reads the numbers back out of a previously generated page,
// so `make bash-suite` can print the delta rather than leaving whoever
// writes the release note to diff two tables by eye. The doc is the
// record of the last run; there is no separate state file to go stale.
var publishedRe = map[string]*regexp.Regexp{
	"strict": regexp.MustCompile(`\|\s*\*\*strict\*\*\s*\|\s*\*\*(\d+)/(\d+) files`),
	"parsed": regexp.MustCompile(`\|\s*parsed\s*\|\s*(\d+)/(\d+) files`),
	"lines":  regexp.MustCompile(`\|\s*line agreement\s*\|\s*(\d+)/(\d+) lines`),
}

// ParsePublishedSuite recovers the last published summary. A page that
// cannot be read yields a zero summary, which SuiteDelta renders as a
// first run — the honest answer when there is nothing to compare to.
func ParsePublishedSuite(doc string) SuiteSummary {
	var s SuiteSummary
	if m := publishedRe["strict"].FindStringSubmatch(doc); m != nil {
		s.Passed, s.Files = atoi(m[1]), atoi(m[2])
	}
	if m := publishedRe["parsed"].FindStringSubmatch(doc); m != nil {
		s.Parsed = atoi(m[1])
	}
	if m := publishedRe["lines"].FindStringSubmatch(doc); m != nil {
		s.MatchedLine, s.BashLines = atoi(m[1]), atoi(m[2])
	}
	return s
}

func atoi(s string) int {
	n, err := strconv.Atoi(s)
	if err != nil {
		return 0
	}
	return n
}
