//go:build unix

package compat

import (
	"bytes"
	"context"
	"errors"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"syscall"
	"time"
)

// The bash suite gate (#211).
//
// The curated corpus (corpus.go) asks "does the stuff people actually
// paste work?" and answers 89%. This asks a harder question with a
// denominator nobody can accuse us of choosing: bash's *own* test suite,
// the tests/ directory shipped in its source tarball.
//
// The move is Bun 1.2's. The answer to a year of "it broke my app" was
// not marketing but adopting the incumbent's own definition of correct
// and publishing per-module pass rates; complaints quieted within
// months. The mechanism is asymmetric — users forgive a documented 5%
// gap and punish an undocumented 1% one, because the undocumented one
// arrives at 2AM.
//
// # Why the suite is not in this repository
//
// Every file in bash's tests/ carries a GPLv3 header, and koi is MIT.
// Vendoring them would relicense this repository by accident, so the
// suite is **fetched, never committed**: `make bash-suite` downloads the
// tarball into build/, and this code reads whatever is there. A machine
// without it skips, loudly.
//
// # Why bash is still the oracle, rather than the shipped .right files
//
// bash's own harness diffs against .right files generated by the version
// that shipped them. Comparing koi to those would fold every difference
// between the local bash and the tarball's bash into koi's score. So the
// same differential discipline as the corpus applies: run each .tests
// file through the *local* bash and through koi, and compare. bash on
// the running machine is the oracle, here as everywhere else.
//
// # Why three numbers instead of one
//
// A single percentage would be actively misleading here, in both
// directions, and the reason is worth stating where the numbers are
// computed:
//
//   - **Strict** is whole-file: identical combined output and identical
//     exit status. It is the number a skeptic should quote, and it is
//     brutal — one wrong line in a 369-line file of deliberate bash
//     arcana fails the file.
//   - **Parsed** is how many files koi can read at all. It matters
//     because koi parses a script *up front*: a single unsupported
//     construct on line 129 forfeits the other 368 lines, so the strict
//     number is dominated by parse coverage rather than by runtime
//     behavior. Reporting only strict would hide that.
//   - **Line agreement** is how much of bash's output koi reproduced
//     exactly. It is the number that says what the shape of the gap is.
//
// The parse errors are the actionable half: they are a ranked list of
// constructs bash's own suite exercises and the substrate cannot read,
// which is exactly the sharper upstream target #119 wanted.

// suiteTimeout bounds one test file. Some of bash's tests wait on
// children; a hang must be a failure rather than a stalled run.
//
// Ten seconds rather than something generous: 83 files run twice, so
// every second of the bound is nearly three minutes of worst-case wall
// clock, and Go's own 10-minute test timeout kills the run before it can
// publish anything. The make target raises that too, but the real fix is
// not to wait 20 seconds on a file that has plainly wedged.
const suiteTimeout = 10 * time.Second

// SuiteResult is one .tests file's verdict.
type SuiteResult struct {
	File               string
	BashOut, KoiOut    string
	BashCode, KoiCode  int
	Pass               bool   // identical output and exit status
	Parsed             bool   // koi read the whole file
	ParseError         string // the construct that stopped it, when it did not
	BashLines, Matched int    // lines bash produced, and how many koi reproduced
}

// SuiteSummary is the published headline.
type SuiteSummary struct {
	Files, Passed, Parsed  int
	BashLines, MatchedLine int
}

// Rate is the strict pass percentage, rounded down — a scoreboard never
// rounds in its own favor.
func (s SuiteSummary) Rate() int {
	if s.Files == 0 {
		return 0
	}
	return s.Passed * 100 / s.Files
}

// ParseRate is the share of files koi can read end to end.
func (s SuiteSummary) ParseRate() int {
	if s.Files == 0 {
		return 0
	}
	return s.Parsed * 100 / s.Files
}

// LineRate is the share of bash's own output koi reproduced exactly.
func (s SuiteSummary) LineRate() int {
	if s.BashLines == 0 {
		return 0
	}
	return s.MatchedLine * 100 / s.BashLines
}

// koiParseErr matches the parser's own report: "koi: ./arith.tests:129:16: …".
// The path is captured, not skipped, because it has to be *checked*.
//
// bash's suite deliberately feeds broken snippets to $THIS_SH to test how
// a shell reports errors, so koi correctly reporting a parse error for an
// intentionally-bad sub-invocation appears in the same output. Matching
// any parse error charged those against the file under test and put the
// parse rate at 67% when it is really 78% — a nine-file error in the
// direction of understating koi, which is the less embarrassing direction
// and still wrong.
var koiParseErr = regexp.MustCompile(`(?m)^koi: (\S+):\d+:\d+: (.+)$`)

// BashSuiteDir returns the fetched tests directory and whether it is
// there. $KOI_BASH_TESTS overrides, so a machine with a bash checkout can
// point at it instead of downloading another copy.
func BashSuiteDir(repoRoot string) (string, bool) {
	if dir := os.Getenv("KOI_BASH_TESTS"); dir != "" {
		if _, err := os.Stat(filepath.Join(dir, "run-all")); err == nil {
			return dir, true
		}
		return dir, false
	}
	dir := filepath.Join(repoRoot, "build", "bash-tests")
	if _, err := os.Stat(filepath.Join(dir, "run-all")); err == nil {
		return dir, true
	}
	return dir, false
}

// SuiteFiles lists the .tests files, sorted, so a published table is
// stable across runs.
func SuiteFiles(dir string) ([]string, error) {
	entries, err := filepath.Glob(filepath.Join(dir, "*.tests"))
	if err != nil {
		return nil, err
	}
	names := make([]string, 0, len(entries))
	for _, e := range entries {
		names = append(names, filepath.Base(e))
	}
	sort.Strings(names)
	return names, nil
}

// RunBashSuite runs every .tests file through both shells.
//
// helpers is the directory holding bash's own recho/zecho/printenv,
// built from support/*.c. Without them both shells print "command not
// found" for most assertions and the comparison measures nothing.
//
// The first run of this scored 0/83, and none of it was koi: the helpers
// were missing *and* the shell under test was being invoked by a path
// that could not execute. Both faults produce "everything fails", which
// is why the harness asserts its own sanity (bash produced output at
// all, koi parsed something at all) rather than trusting a zero.
func RunBashSuite(ctx context.Context, bashBin, koiBin, dir, helpers string) ([]SuiteResult, error) {
	files, err := SuiteFiles(dir)
	if err != nil {
		return nil, err
	}
	if len(files) == 0 {
		return nil, errors.New("no .tests files: run `make bash-suite` to fetch them")
	}
	results := make([]SuiteResult, 0, len(files))
	for _, f := range files {
		r := SuiteResult{File: f}
		r.BashOut, r.BashCode = runSuiteFile(ctx, bashBin, dir, helpers, f)
		r.KoiOut, r.KoiCode = runSuiteFile(ctx, koiBin, dir, helpers, f)

		r.ParseError = ParseErrorFor(f, r.KoiOut)
		r.Parsed = r.ParseError == ""
		r.Pass = r.BashOut == r.KoiOut && r.BashCode == r.KoiCode
		r.BashLines, r.Matched = agreement(r.BashOut, r.KoiOut)
		results = append(results, r)
	}
	return results, nil
}

// runSuiteFile runs one test the way bash's own harness does: from
// inside tests/, with THIS_SH naming the shell under test, since the
// files re-invoke it for subshell cases.
func runSuiteFile(ctx context.Context, shell, dir, helpers, file string) (string, int) {
	rctx, cancel := context.WithTimeout(ctx, suiteTimeout)
	defer cancel()
	cmd := exec.CommandContext(rctx, shell, "./"+file) //nolint:gosec // fixed shells, fetched corpus
	cmd.Dir = dir
	// Kill the whole process group, and stop waiting on the pipe.
	//
	// This is why the first complete run took the full 30-minute test
	// timeout instead of the four minutes the same work takes from a
	// shell: bash's tests spawn children, CommandContext kills only the
	// direct child, and Run then blocks forever waiting for a
	// bytes.Buffer copy that cannot finish while a surviving grandchild
	// still holds the write end of the pipe. A prototype driven by
	// timeout(1) never showed it, because timeout(1) signals the group.
	//
	// Setpgid puts every descendant in one group so Cancel can signal all
	// of them; WaitDelay is the backstop for the case where something
	// ignores the signal, since a gate that hangs is worse than a gate
	// that reports a failure.
	cmd.SysProcAttr = &syscall.SysProcAttr{Setpgid: true}
	cmd.Cancel = func() error {
		if cmd.Process == nil {
			return nil
		}
		return syscall.Kill(-cmd.Process.Pid, syscall.SIGKILL)
	}
	cmd.WaitDelay = 2 * time.Second
	// A scratch HOME, not the real one. bash's suite writes files and some
	// cases read $HOME; the repo's rule is that tests never touch real
	// user state, and it applies most of all to a corpus we did not write
	// and do not audit. TMPDIR goes with it so a stray temp file lands in
	// the same place and is removed with it.
	home, herr := os.MkdirTemp("", "koi-bash-suite-")
	if herr != nil {
		return "[runner error: " + herr.Error() + "]", -1
	}
	defer os.RemoveAll(home) //nolint:errcheck // scratch dir
	cmd.Env = []string{
		"PATH=" + helpers + string(os.PathListSeparator) + os.Getenv("PATH"),
		"HOME=" + home,
		"TMPDIR=" + home,
		"THIS_SH=" + shell,
		"LC_ALL=C",
		"TERM=dumb",
		"KOI_WELCOME=off",
	}
	var buf bytes.Buffer
	cmd.Stdout, cmd.Stderr = &buf, &buf
	err := cmd.Run()
	code := 0
	var exit *exec.ExitError
	if errors.As(err, &exit) {
		code = exit.ExitCode()
	} else if err != nil {
		return buf.String() + "\n[runner error: " + err.Error() + "]", -1
	}
	return buf.String(), code
}

// agreement counts how many of bash's output lines koi also produced, as
// a longest common subsequence.
//
// Positional comparison was tried first and rejected: koi printing one
// extra line near the top shifts every later line out of position, so a
// file that agreed almost everywhere scored near zero. That measures
// alignment, not compatibility. An LCS resynchronises after a
// difference, which is what makes the number describe the *shape* of the
// gap rather than the position of its first occurrence — and it is what
// diff itself reports, so the figure can be checked by hand.
func agreement(bashOut, koiOut string) (total, matched int) {
	b := strings.Split(bashOut, "\n")
	k := strings.Split(koiOut, "\n")
	total = len(b)
	if len(b) == 0 || len(k) == 0 {
		return total, 0
	}
	// Two rows rather than a full table: these files run to a few hundred
	// lines and only the previous row is ever read.
	prev := make([]int, len(k)+1)
	cur := make([]int, len(k)+1)
	for i := 1; i <= len(b); i++ {
		for j := 1; j <= len(k); j++ {
			if b[i-1] == k[j-1] {
				cur[j] = prev[j-1] + 1
			} else if prev[j] >= cur[j-1] {
				cur[j] = prev[j]
			} else {
				cur[j] = cur[j-1]
			}
		}
		prev, cur = cur, prev
	}
	return total, prev[len(k)]
}

// SummarizeSuite tallies the run.
func SummarizeSuite(results []SuiteResult) SuiteSummary {
	var s SuiteSummary
	for _, r := range results {
		s.Files++
		if r.Pass {
			s.Passed++
		}
		if r.Parsed {
			s.Parsed++
		}
		s.BashLines += r.BashLines
		s.MatchedLine += r.Matched
	}
	return s
}

// ParseGaps ranks the constructs that stopped koi reading a file, most
// frequent first. This is the list #119 should be worked from.
func ParseGaps(results []SuiteResult) []ParseGap {
	counts := map[string][]string{}
	for _, r := range results {
		if r.ParseError == "" {
			continue
		}
		counts[r.ParseError] = append(counts[r.ParseError], r.File)
	}
	gaps := make([]ParseGap, 0, len(counts))
	for msg, files := range counts {
		sort.Strings(files)
		gaps = append(gaps, ParseGap{Message: msg, Files: files})
	}
	sort.Slice(gaps, func(i, j int) bool {
		if len(gaps[i].Files) != len(gaps[j].Files) {
			return len(gaps[i].Files) > len(gaps[j].Files)
		}
		return gaps[i].Message < gaps[j].Message
	})
	return gaps
}

// ParseGap is one construct the substrate cannot read, and where.
type ParseGap struct {
	Message string
	Files   []string
}

// ParseErrorFor returns the parse error that stopped koi reading file,
// or "" if koi read it.
//
// Only an error naming *this* file counts. bash's suite deliberately
// feeds broken snippets to $THIS_SH to test how a shell reports errors,
// so koi correctly reporting a parse error for an intentionally-bad
// sub-invocation appears in the same output; charging those against the
// file under test put the parse rate at 67% when it is 78%.
func ParseErrorFor(file, out string) string {
	for _, m := range koiParseErr.FindAllStringSubmatch(out, -1) {
		if m[1] == "./"+file || m[1] == file {
			return strings.TrimSpace(m[2])
		}
	}
	return ""
}
