package compat

import (
	"fmt"
	"strings"
)

// Scoreboard renders docs/compat.md: the published, numeric,
// argue-with-it compat claim (#101). The generator lives next to the
// corpus so the doc can never drift from the run that produced it.
func Scoreboard(results []Result, bashVersion string) string {
	s := Summarize(results)
	var b strings.Builder

	b.WriteString("# bash compatibility scoreboard\n\n")
	b.WriteString("*Generated by `make compat` from `internal/compat` — do not edit by hand.*\n\n")
	fmt.Fprintf(&b, "**%d of %d cases pass (%d%%)** against %s.\n\n",
		s.Passed, s.Total, s.Rate(), bashVersion)
	b.WriteString(`Every case runs the same script through real bash and through
` + "`koi -c`" + `, comparing combined output *and* exit status. bash on the
running machine is the oracle — nothing here encodes what we think bash
ought to do. Cases are curated around what people actually paste into a
new shell (tool init hooks, install one-liners, parameter expansion,
arrays, process substitution), not around the bash manual's table of
contents; each carries its provenance in the corpus.

`)
	b.WriteString("## By category\n\n| category | passing |\n| --- | --- |\n")
	for _, cat := range Categories() {
		counts := s.ByCategory[cat]
		fmt.Fprintf(&b, "| %s | %d/%d |\n", cat, counts[0], counts[1])
	}

	failures := Failures(results)
	b.WriteString("\n## Known gaps\n\n")
	if len(failures) == 0 {
		b.WriteString("None in the current corpus. That is a statement about the corpus as much as the shell — see \"Honesty notes\".\n")
	} else {
		b.WriteString("| case | category | difference |\n| --- | --- | --- |\n")
		for _, r := range failures {
			fmt.Fprintf(&b, "| %s | %s | %s |\n", r.Name, r.Category, escapePipes(r.Diff()))
		}
		b.WriteString(`
Parser gaps are koi's own since the substrate lift: ` + "`syntax`" + `,
` + "`pattern`" + `, ` + "`interp`" + ` and ` + "`expand`" + ` are all maintained in
` + "`internal/shell`" + `, so a parse gap and a runtime gap are the same kind of
work now. Every gap is kept with a minimal reproduction. Shell-identity behavior (` + "`BASH_VERSION`" + ` and tool
init hooks) is a deliberate decision, not a bug — see the decisions in
[design.md](design.md).
`)
	}

	b.WriteString(`
## The other denominator

This corpus is curated, which is both its strength and its limit: it asks
whether the things people actually paste work, against a set of cases we
chose ourselves. The harder number runs **bash's own test suite** — a
denominator nobody can accuse us of picking — and is published separately
in [docs/bash-suite.md](bash-suite.md). Expect it to be far lower. Both
are true and they answer different questions; quote whichever one the
claim is actually about.

## Honesty notes

- A pass means *this snippet behaves identically*, not that the feature
  is complete. Corpus coverage is the ceiling on what this number can
  claim.
- The corpus grows; the percentage can therefore fall without the shell
  regressing. That is the point — a scoreboard that only goes up is
  marketing.
- Regressions fail CI: ` + "`make compat-check`" + ` re-runs the corpus and
  refuses a lower pass count than this file records.
- Interactive behavior (line editing, completion, prompts) is out of
  scope here; this measures the scripting substrate only.
- **Which bash you compare against changes the answer.** macOS still
  ships bash 3.2 (2007, the last GPLv2 release), where *bash itself*
  rejects ` + "`${s,,}`" + ` and ` + "`declare -A`" + ` — against that oracle koi is
  *ahead* on those cases, and the differential dutifully reports a
  difference. The number above is against the bash named in the
  headline; CI enforces the regression gate only when the runner's
  bash major matches, and reports without enforcing otherwise.
`)
	return b.String()
}

func escapePipes(s string) string { return strings.ReplaceAll(s, "|", `\|`) }
