package compat

import (
	"fmt"
	"strings"
)

// Scoreboard renders docs/compat.md: the published, numeric,
// argue-with-it compat claim (#101). The generator lives next to the
// corpus so the doc can never drift from the run that produced it.
func Scoreboard(results []Result, bashVersion string) string {
	s := Summarize(results)
	var b strings.Builder

	b.WriteString("# bash compatibility scoreboard\n\n")
	b.WriteString("*Generated by `make compat` from `internal/compat` — do not edit by hand.*\n\n")
	fmt.Fprintf(&b, "**%d of %d cases pass (%d%%)** against %s.\n\n",
		s.Passed, s.Total, s.Rate(), bashVersion)
	b.WriteString(`Every case runs the same script through real bash and through
` + "`gish -c`" + `, comparing combined output *and* exit status. bash on the
running machine is the oracle — nothing here encodes what we think bash
ought to do. Cases are curated around what people actually paste into a
new shell (tool init hooks, install one-liners, parameter expansion,
arrays, process substitution), not around the bash manual's table of
contents; each carries its provenance in the corpus.

`)
	b.WriteString("## By category\n\n| category | passing |\n| --- | --- |\n")
	for _, cat := range Categories() {
		counts := s.ByCategory[cat]
		fmt.Fprintf(&b, "| %s | %d/%d |\n", cat, counts[0], counts[1])
	}

	failures := Failures(results)
	b.WriteString("\n## Known gaps\n\n")
	if len(failures) == 0 {
		b.WriteString("None in the current corpus. That is a statement about the corpus as much as the shell — see \"Honesty notes\".\n")
	} else {
		b.WriteString("| case | category | difference |\n| --- | --- | --- |\n")
		for _, r := range failures {
			fmt.Fprintf(&b, "| %s | %s | %s |\n", r.Name, r.Category, escapePipes(r.Diff()))
		}
		b.WriteString(`
Gaps in the substrate belong upstream at [mvdan/sh](https://github.com/mvdan/sh) —
fixing them there improves every consumer, not just gish. The current
set is tracked in [#119](https://github.com/blairham/gish/issues/119)
with minimal reproductions. Shell-identity behavior (` + "`BASH_VERSION`" + `
and tool init hooks) is a deliberate open decision, not a bug:
[#120](https://github.com/blairham/gish/issues/120).
`)
	}

	b.WriteString(`
## Honesty notes

- A pass means *this snippet behaves identically*, not that the feature
  is complete. Corpus coverage is the ceiling on what this number can
  claim.
- The corpus grows; the percentage can therefore fall without the shell
  regressing. That is the point — a scoreboard that only goes up is
  marketing.
- Regressions fail CI: ` + "`make compat-check`" + ` re-runs the corpus and
  refuses a lower pass count than this file records.
- Interactive behavior (line editing, completion, prompts) is out of
  scope here; this measures the scripting substrate only.
`)
	return b.String()
}

func escapePipes(s string) string { return strings.ReplaceAll(s, "|", `\|`) }
