//go:build unix

package compat

import (
	"fmt"
	"strings"
)

// InteractiveDoc renders docs/interactive-compat.md: the paste gate and
// the source gate (#161) and the ecosystem matrix (#159), published
// next to the script scoreboard.
//
// They are one document because they answer one question — "does the
// thing I was going to do on my first afternoon work?" — and because
// separating them would let the flattering part be quoted alone.
func InteractiveDoc(paste []PasteResult, source []SourceResult, eco []EcosystemResult, bashVersion string) string {
	var b strings.Builder

	passed := 0
	for _, r := range paste {
		if r.Pass {
			passed++
		}
	}
	ran, sourcePassed := 0, 0
	for _, r := range source {
		if !r.Present {
			continue
		}
		ran++
		if r.Pass {
			sourcePassed++
		}
	}

	b.WriteString("# interactive compatibility: paste, source, and the ecosystem\n\n")
	b.WriteString("*Generated by `make paste-gate` from `internal/compat` — do not edit by hand.*\n\n")
	fmt.Fprintf(&b, "**Paste gate: %d of %d cases pass.** ", passed, len(paste))
	fmt.Fprintf(&b, "**Source gate: %d of %d installed tools pass** (%d of %d not installed on the machine that generated this).\n\n",
		sourcePassed, ran, len(source)-ran, len(source))
	ecoRan, ecoPassed := 0, 0
	for _, r := range eco {
		if !r.Present {
			continue
		}
		ecoRan++
		if r.Pass {
			ecoPassed++
		}
	}
	fmt.Fprintf(&b, "**Ecosystem matrix: %d of %d installed tools pass** (%d of %d not installed here).\n\n",
		ecoPassed, ecoRan, len(eco)-ecoRan, len(eco))
	b.WriteString("Oracle: " + bashVersion + ".\n\n")

	b.WriteString(`"Pasted bash one-liners and sourced bash scripts fail" is the top
abandonment cause on two independent corpora — 22 first-person accounts
across a decade on HN/Lobsters, and 27 of 62 churn accounts on Reddit.
[docs/compat.md](compat.md) scores bash *scripts* through ` + "`koi -c`" + `.
This page covers the two paths that scoreboard does not: text pasted at
an interactive prompt, and real init scripts sourced unmodified.

The distinction is not academic. A pasted line goes through bracketed
paste, the line editor, history expansion, the diagnostics pass and the
accept-or-continue decision before the interpreter sees it — five places
a line can change meaning, none of them exercised by running a script.

## Paste gate

Each case is pasted into a real interactive koi on a pty, as a
terminal delivers a paste, and Enter is pressed. Output is read from
between the OSC 133 semantic marks, so there is no guessing where the
prompt ended. bash is the oracle: the same text is run through real
bash and the results must agree.

| case | result | provenance |
| --- | --- | --- |
`)
	for _, r := range paste {
		verdict := "✅"
		if !r.Pass {
			verdict = "❌ " + escapePipes(r.Reason)
		}
		fmt.Fprintf(&b, "| %s | %s | %s |\n", escapePipes(r.Name), verdict, escapePipes(r.Provenance))
	}

	b.WriteString(`
## Source gate

The named breakers, sourced **unmodified** as installed on the machine,
then probed for what they defined. Differential again: the same
load-and-probe script through bash and through koi.

A tool that is not installed is listed as such rather than dropped —
"every case we ran passed" means nothing without the list of what was
not run.

| tool | result | provenance |
| --- | --- | --- |
`)
	for _, r := range source {
		verdict := "✅"
		switch {
		case !r.Present:
			verdict = "— not installed here"
		case !r.Pass:
			verdict = "❌ " + escapePipes(r.Reason)
		}
		fmt.Fprintf(&b, "| %s | %s | %s |\n", escapePipes(r.Name), verdict, escapePipes(r.Provenance))
	}

	b.WriteString(`
## Ecosystem matrix

The point of implementing bash's hook surface is that the tools people
already have keep working. This is that claim, measured: each tool is
installed unmodified, **its own documented init line** is sourced, and
its behavior is asserted in a live interactive koi on a pty — the
prompt renders, the widget binds, the environment changes on cd.

| tool | result | what it proves |
| --- | --- | --- |
`)
	for _, r := range eco {
		verdict := "✅"
		switch {
		case !r.Present:
			verdict = "— not installed here"
		case !r.Pass:
			verdict = "❌ " + escapePipes(r.Reason)
		}
		fmt.Fprintf(&b, "| %s | %s | %s |\n", escapePipes(r.Name), verdict, escapePipes(r.Asserts))
	}

	b.WriteString(`
## Honesty notes

- The source gate's coverage depends on what is installed where it runs.
  CI runners carry a different set than a developer laptop, so the
  numbers in this file describe the machine that generated it, and the
  gate enforces "no fewer passes among the tools that *were* present".
- The paste gate asks bash the same question wherever the two paths ask
  the same thing. History expansion is the exception: it is off in
  bash's non-interactive mode, so those cases name the equivalent
  command they pose to bash instead, in the corpus, where it can be
  argued with.
- A pass means the pasted text behaved identically, not that every
  construct in that family is supported.
- Regressions fail CI (` + "`make paste-gate-check`" + `).
`)
	return b.String()
}
