// AIProvider — model access as an interchangeable plugin (#20), never a
// hardcoded vendor. The shell owns the hooks (the ?? compose prefix,
// the explain builtin) and the context assembly; a provider owns the
// model call — Claude API, claude CLI, local models, all behind one
// contract.
//
// Correctness rules, enforced shell-side:
//   - Explicitly invoked only. Nothing streams keystrokes to a model;
//     a request exists because the user asked.
//   - Preview-before-execute. Compose results land in the editor
//     buffer as text; the user runs them (and by default they arrive
//     wrapped in a #21 sandbox invocation, visible and removable).
//   - Scrubbed context. The recent-command context comes from the
//     history store, which never records secret-bearing commands
//     (#10), and the env map is the standard allowlist.
//
// Latency is human-scale (explicitly invoked, never on the keystroke
// path) — the host allows a long deadline and Ctrl-C cancels.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: gish/plugin/v1/ai.proto

package pluginapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ShellContext is the shell's unfair advantage: real session state,
// assembled host-side and already scrubbed. Absent fields are unknown.
type ShellContext struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Cwd   string                 `protobuf:"bytes,1,opt,name=cwd,proto3" json:"cwd,omitempty"`
	// Most recent commands, newest first, from the history store — which
	// never contains secret-bearing commands.
	RecentCommands []string `protobuf:"bytes,2,rep,name=recent_commands,json=recentCommands,proto3" json:"recent_commands,omitempty"`
	LastExitCode   int32    `protobuf:"varint,3,opt,name=last_exit_code,json=lastExitCode,proto3" json:"last_exit_code,omitempty"`
	// Tail of the failing command's output. Reserved until the shell
	// captures command output; empty today.
	OutputTail string `protobuf:"bytes,4,opt,name=output_tail,json=outputTail,proto3" json:"output_tail,omitempty"`
	// Allowlisted environment subset (the filtered-env invariant).
	Env map[string]string `protobuf:"bytes,5,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// "darwin", "linux", … — command dialects differ.
	Os            string `protobuf:"bytes,6,opt,name=os,proto3" json:"os,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellContext) Reset() {
	*x = ShellContext{}
	mi := &file_gish_plugin_v1_ai_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellContext) ProtoMessage() {}

func (x *ShellContext) ProtoReflect() protoreflect.Message {
	mi := &file_gish_plugin_v1_ai_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellContext.ProtoReflect.Descriptor instead.
func (*ShellContext) Descriptor() ([]byte, []int) {
	return file_gish_plugin_v1_ai_proto_rawDescGZIP(), []int{0}
}

func (x *ShellContext) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *ShellContext) GetRecentCommands() []string {
	if x != nil {
		return x.RecentCommands
	}
	return nil
}

func (x *ShellContext) GetLastExitCode() int32 {
	if x != nil {
		return x.LastExitCode
	}
	return 0
}

func (x *ShellContext) GetOutputTail() string {
	if x != nil {
		return x.OutputTail
	}
	return ""
}

func (x *ShellContext) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ShellContext) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

type ComposeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The user's natural-language request, verbatim.
	Query         string        `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Context       *ShellContext `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	EventSeq      uint64        `protobuf:"varint,3,opt,name=event_seq,json=eventSeq,proto3" json:"event_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComposeRequest) Reset() {
	*x = ComposeRequest{}
	mi := &file_gish_plugin_v1_ai_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComposeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComposeRequest) ProtoMessage() {}

func (x *ComposeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gish_plugin_v1_ai_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComposeRequest.ProtoReflect.Descriptor instead.
func (*ComposeRequest) Descriptor() ([]byte, []int) {
	return file_gish_plugin_v1_ai_proto_rawDescGZIP(), []int{1}
}

func (x *ComposeRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ComposeRequest) GetContext() *ShellContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *ComposeRequest) GetEventSeq() uint64 {
	if x != nil {
		return x.EventSeq
	}
	return 0
}

type ComposeCandidate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The proposed command, ready for the editor buffer. Raw command
	// only — the host owns any sandbox wrapping.
	Command string `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	// One-line rationale, shown as a comment above the buffer.
	Explanation string `protobuf:"bytes,2,opt,name=explanation,proto3" json:"explanation,omitempty"`
	// Last candidate of the stream.
	Final         bool `protobuf:"varint,4,opt,name=final,proto3" json:"final,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComposeCandidate) Reset() {
	*x = ComposeCandidate{}
	mi := &file_gish_plugin_v1_ai_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComposeCandidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComposeCandidate) ProtoMessage() {}

func (x *ComposeCandidate) ProtoReflect() protoreflect.Message {
	mi := &file_gish_plugin_v1_ai_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComposeCandidate.ProtoReflect.Descriptor instead.
func (*ComposeCandidate) Descriptor() ([]byte, []int) {
	return file_gish_plugin_v1_ai_proto_rawDescGZIP(), []int{2}
}

func (x *ComposeCandidate) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ComposeCandidate) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

func (x *ComposeCandidate) GetFinal() bool {
	if x != nil {
		return x.Final
	}
	return false
}

type ExplainRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The command being explained (from the history store, scrub-safe).
	Command       string        `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	ExitCode      int32         `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Context       *ShellContext `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExplainRequest) Reset() {
	*x = ExplainRequest{}
	mi := &file_gish_plugin_v1_ai_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExplainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExplainRequest) ProtoMessage() {}

func (x *ExplainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gish_plugin_v1_ai_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExplainRequest.ProtoReflect.Descriptor instead.
func (*ExplainRequest) Descriptor() ([]byte, []int) {
	return file_gish_plugin_v1_ai_proto_rawDescGZIP(), []int{3}
}

func (x *ExplainRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ExplainRequest) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExplainRequest) GetContext() *ShellContext {
	if x != nil {
		return x.Context
	}
	return nil
}

type ExplainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Explanation   string                 `protobuf:"bytes,1,opt,name=explanation,proto3" json:"explanation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExplainResponse) Reset() {
	*x = ExplainResponse{}
	mi := &file_gish_plugin_v1_ai_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExplainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExplainResponse) ProtoMessage() {}

func (x *ExplainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gish_plugin_v1_ai_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExplainResponse.ProtoReflect.Descriptor instead.
func (*ExplainResponse) Descriptor() ([]byte, []int) {
	return file_gish_plugin_v1_ai_proto_rawDescGZIP(), []int{4}
}

func (x *ExplainResponse) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

var File_gish_plugin_v1_ai_proto protoreflect.FileDescriptor

const file_gish_plugin_v1_ai_proto_rawDesc = "" +
	"\n" +
	"\x17gish/plugin/v1/ai.proto\x12\x0egish.plugin.v1\"\x91\x02\n" +
	"\fShellContext\x12\x10\n" +
	"\x03cwd\x18\x01 \x01(\tR\x03cwd\x12'\n" +
	"\x0frecent_commands\x18\x02 \x03(\tR\x0erecentCommands\x12$\n" +
	"\x0elast_exit_code\x18\x03 \x01(\x05R\flastExitCode\x12\x1f\n" +
	"\voutput_tail\x18\x04 \x01(\tR\n" +
	"outputTail\x127\n" +
	"\x03env\x18\x05 \x03(\v2%.gish.plugin.v1.ShellContext.EnvEntryR\x03env\x12\x0e\n" +
	"\x02os\x18\x06 \x01(\tR\x02os\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"{\n" +
	"\x0eComposeRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x126\n" +
	"\acontext\x18\x02 \x01(\v2\x1c.gish.plugin.v1.ShellContextR\acontext\x12\x1b\n" +
	"\tevent_seq\x18\x03 \x01(\x04R\beventSeq\"d\n" +
	"\x10ComposeCandidate\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12 \n" +
	"\vexplanation\x18\x02 \x01(\tR\vexplanation\x12\x14\n" +
	"\x05final\x18\x04 \x01(\bR\x05final\"\x7f\n" +
	"\x0eExplainRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x1b\n" +
	"\texit_code\x18\x02 \x01(\x05R\bexitCode\x126\n" +
	"\acontext\x18\x03 \x01(\v2\x1c.gish.plugin.v1.ShellContextR\acontext\"3\n" +
	"\x0fExplainResponse\x12 \n" +
	"\vexplanation\x18\x01 \x01(\tR\vexplanation2\xa7\x01\n" +
	"\n" +
	"AIProvider\x12M\n" +
	"\aCompose\x12\x1e.gish.plugin.v1.ComposeRequest\x1a .gish.plugin.v1.ComposeCandidate0\x01\x12J\n" +
	"\aExplain\x12\x1e.gish.plugin.v1.ExplainRequest\x1a\x1f.gish.plugin.v1.ExplainResponseB2Z0github.com/blairham/gish/pkg/pluginapi;pluginapib\x06proto3"

var (
	file_gish_plugin_v1_ai_proto_rawDescOnce sync.Once
	file_gish_plugin_v1_ai_proto_rawDescData []byte
)

func file_gish_plugin_v1_ai_proto_rawDescGZIP() []byte {
	file_gish_plugin_v1_ai_proto_rawDescOnce.Do(func() {
		file_gish_plugin_v1_ai_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gish_plugin_v1_ai_proto_rawDesc), len(file_gish_plugin_v1_ai_proto_rawDesc)))
	})
	return file_gish_plugin_v1_ai_proto_rawDescData
}

var file_gish_plugin_v1_ai_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_gish_plugin_v1_ai_proto_goTypes = []any{
	(*ShellContext)(nil),     // 0: gish.plugin.v1.ShellContext
	(*ComposeRequest)(nil),   // 1: gish.plugin.v1.ComposeRequest
	(*ComposeCandidate)(nil), // 2: gish.plugin.v1.ComposeCandidate
	(*ExplainRequest)(nil),   // 3: gish.plugin.v1.ExplainRequest
	(*ExplainResponse)(nil),  // 4: gish.plugin.v1.ExplainResponse
	nil,                      // 5: gish.plugin.v1.ShellContext.EnvEntry
}
var file_gish_plugin_v1_ai_proto_depIdxs = []int32{
	5, // 0: gish.plugin.v1.ShellContext.env:type_name -> gish.plugin.v1.ShellContext.EnvEntry
	0, // 1: gish.plugin.v1.ComposeRequest.context:type_name -> gish.plugin.v1.ShellContext
	0, // 2: gish.plugin.v1.ExplainRequest.context:type_name -> gish.plugin.v1.ShellContext
	1, // 3: gish.plugin.v1.AIProvider.Compose:input_type -> gish.plugin.v1.ComposeRequest
	3, // 4: gish.plugin.v1.AIProvider.Explain:input_type -> gish.plugin.v1.ExplainRequest
	2, // 5: gish.plugin.v1.AIProvider.Compose:output_type -> gish.plugin.v1.ComposeCandidate
	4, // 6: gish.plugin.v1.AIProvider.Explain:output_type -> gish.plugin.v1.ExplainResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_gish_plugin_v1_ai_proto_init() }
func file_gish_plugin_v1_ai_proto_init() {
	if File_gish_plugin_v1_ai_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gish_plugin_v1_ai_proto_rawDesc), len(file_gish_plugin_v1_ai_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gish_plugin_v1_ai_proto_goTypes,
		DependencyIndexes: file_gish_plugin_v1_ai_proto_depIdxs,
		MessageInfos:      file_gish_plugin_v1_ai_proto_msgTypes,
	}.Build()
	File_gish_plugin_v1_ai_proto = out.File
	file_gish_plugin_v1_ai_proto_goTypes = nil
	file_gish_plugin_v1_ai_proto_depIdxs = nil
}
