// AIProvider — model access as an interchangeable plugin (#20), never a
// hardcoded vendor. The shell owns the hooks (the ?? compose prefix,
// the explain builtin) and the context assembly; a provider owns the
// model call — Claude API, claude CLI, local models, all behind one
// contract.
//
// Correctness rules, enforced shell-side:
//   - Explicitly invoked only. Nothing streams keystrokes to a model;
//     a request exists because the user asked.
//   - Preview-before-execute. Compose results land in the editor
//     buffer as text; the user runs them (and by default they arrive
//     wrapped in a #21 sandbox invocation, visible and removable).
//   - Scrubbed context. The recent-command context comes from the
//     history store, which never records secret-bearing commands
//     (#10), and the env map is the standard allowlist.
//
// Latency is human-scale (explicitly invoked, never on the keystroke
// path) — the host allows a long deadline and Ctrl-C cancels.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: gish/plugin/v1/ai.proto

package pluginapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AIProvider_Compose_FullMethodName = "/gish.plugin.v1.AIProvider/Compose"
	AIProvider_Explain_FullMethodName = "/gish.plugin.v1.AIProvider/Explain"
	AIProvider_Plan_FullMethodName    = "/gish.plugin.v1.AIProvider/Plan"
)

// AIProviderClient is the client API for AIProvider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AIProviderClient interface {
	// Compose turns natural language into command candidates, streamed
	// best-first so the first candidate can land while alternatives are
	// still generating.
	Compose(ctx context.Context, in *ComposeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ComposeCandidate], error)
	// Explain answers "why did that fail" (or "what does this do") for
	// one command.
	Explain(ctx context.Context, in *ExplainRequest, opts ...grpc.CallOption) (*ExplainResponse, error)
	// Plan turns a multi-step task into a spec the user approves before
	// anything runs (#34). The provider only proposes: execution,
	// approval gates, and sandboxing are the shell's, and a plugin never
	// holds an exec channel.
	Plan(ctx context.Context, in *PlanRequest, opts ...grpc.CallOption) (*PlanResponse, error)
}

type aIProviderClient struct {
	cc grpc.ClientConnInterface
}

func NewAIProviderClient(cc grpc.ClientConnInterface) AIProviderClient {
	return &aIProviderClient{cc}
}

func (c *aIProviderClient) Compose(ctx context.Context, in *ComposeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ComposeCandidate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AIProvider_ServiceDesc.Streams[0], AIProvider_Compose_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ComposeRequest, ComposeCandidate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AIProvider_ComposeClient = grpc.ServerStreamingClient[ComposeCandidate]

func (c *aIProviderClient) Explain(ctx context.Context, in *ExplainRequest, opts ...grpc.CallOption) (*ExplainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExplainResponse)
	err := c.cc.Invoke(ctx, AIProvider_Explain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIProviderClient) Plan(ctx context.Context, in *PlanRequest, opts ...grpc.CallOption) (*PlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlanResponse)
	err := c.cc.Invoke(ctx, AIProvider_Plan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AIProviderServer is the server API for AIProvider service.
// All implementations must embed UnimplementedAIProviderServer
// for forward compatibility.
type AIProviderServer interface {
	// Compose turns natural language into command candidates, streamed
	// best-first so the first candidate can land while alternatives are
	// still generating.
	Compose(*ComposeRequest, grpc.ServerStreamingServer[ComposeCandidate]) error
	// Explain answers "why did that fail" (or "what does this do") for
	// one command.
	Explain(context.Context, *ExplainRequest) (*ExplainResponse, error)
	// Plan turns a multi-step task into a spec the user approves before
	// anything runs (#34). The provider only proposes: execution,
	// approval gates, and sandboxing are the shell's, and a plugin never
	// holds an exec channel.
	Plan(context.Context, *PlanRequest) (*PlanResponse, error)
	mustEmbedUnimplementedAIProviderServer()
}

// UnimplementedAIProviderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAIProviderServer struct{}

func (UnimplementedAIProviderServer) Compose(*ComposeRequest, grpc.ServerStreamingServer[ComposeCandidate]) error {
	return status.Error(codes.Unimplemented, "method Compose not implemented")
}
func (UnimplementedAIProviderServer) Explain(context.Context, *ExplainRequest) (*ExplainResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Explain not implemented")
}
func (UnimplementedAIProviderServer) Plan(context.Context, *PlanRequest) (*PlanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Plan not implemented")
}
func (UnimplementedAIProviderServer) mustEmbedUnimplementedAIProviderServer() {}
func (UnimplementedAIProviderServer) testEmbeddedByValue()                    {}

// UnsafeAIProviderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AIProviderServer will
// result in compilation errors.
type UnsafeAIProviderServer interface {
	mustEmbedUnimplementedAIProviderServer()
}

func RegisterAIProviderServer(s grpc.ServiceRegistrar, srv AIProviderServer) {
	// If the following call panics, it indicates UnimplementedAIProviderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AIProvider_ServiceDesc, srv)
}

func _AIProvider_Compose_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ComposeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AIProviderServer).Compose(m, &grpc.GenericServerStream[ComposeRequest, ComposeCandidate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AIProvider_ComposeServer = grpc.ServerStreamingServer[ComposeCandidate]

func _AIProvider_Explain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExplainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIProviderServer).Explain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIProvider_Explain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIProviderServer).Explain(ctx, req.(*ExplainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIProvider_Plan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIProviderServer).Plan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIProvider_Plan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIProviderServer).Plan(ctx, req.(*PlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AIProvider_ServiceDesc is the grpc.ServiceDesc for AIProvider service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AIProvider_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gish.plugin.v1.AIProvider",
	HandlerType: (*AIProviderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Explain",
			Handler:    _AIProvider_Explain_Handler,
		},
		{
			MethodName: "Plan",
			Handler:    _AIProvider_Plan_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Compose",
			Handler:       _AIProvider_Compose_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "gish/plugin/v1/ai.proto",
}
