// CommandProvider — plugins registering shell commands over gRPC (#11):
// the cloudctl pattern applied to a shell. A registered command runs
// like a builtin: dispatched by name before PATH lookup, with its I/O
// streamed over the connection.
//
// Precedence rules (decided on #11): interpreter and gish-native builtin
// names are reserved — claims on them are rejected. Shell functions
// shadow plugin commands (the user always wins). Plugin commands shadow
// PATH binaries, like functions do. Between plugins, the
// lexicographically first plugin name wins a contested command.
//
// v1 streams stdin/stdout/stderr; there is no raw-terminal handover —
// full-screen commands are out of scope until a PTY-passing design
// exists. Execution starts at Enter (never the keystroke path), so Run
// carries no latency budget; cancellation rides the command context.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: gish/plugin/v1/command.proto

package pluginapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommandsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandsRequest) Reset() {
	*x = CommandsRequest{}
	mi := &file_gish_plugin_v1_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandsRequest) ProtoMessage() {}

func (x *CommandsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gish_plugin_v1_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandsRequest.ProtoReflect.Descriptor instead.
func (*CommandsRequest) Descriptor() ([]byte, []int) {
	return file_gish_plugin_v1_command_proto_rawDescGZIP(), []int{0}
}

type CommandSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Command name as typed by the user (e.g. "jump").
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// One-line description, shown by the `plugins` builtin.
	Summary       string `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandSpec) Reset() {
	*x = CommandSpec{}
	mi := &file_gish_plugin_v1_command_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandSpec) ProtoMessage() {}

func (x *CommandSpec) ProtoReflect() protoreflect.Message {
	mi := &file_gish_plugin_v1_command_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandSpec.ProtoReflect.Descriptor instead.
func (*CommandSpec) Descriptor() ([]byte, []int) {
	return file_gish_plugin_v1_command_proto_rawDescGZIP(), []int{1}
}

func (x *CommandSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CommandSpec) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

type CommandsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Commands      []*CommandSpec         `protobuf:"bytes,1,rep,name=commands,proto3" json:"commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandsResponse) Reset() {
	*x = CommandsResponse{}
	mi := &file_gish_plugin_v1_command_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandsResponse) ProtoMessage() {}

func (x *CommandsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gish_plugin_v1_command_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandsResponse.ProtoReflect.Descriptor instead.
func (*CommandsResponse) Descriptor() ([]byte, []int) {
	return file_gish_plugin_v1_command_proto_rawDescGZIP(), []int{2}
}

func (x *CommandsResponse) GetCommands() []*CommandSpec {
	if x != nil {
		return x.Commands
	}
	return nil
}

type RunInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Input:
	//
	//	*RunInput_Start
	//	*RunInput_Stdin
	//	*RunInput_StdinEof
	Input         isRunInput_Input `protobuf_oneof:"input"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunInput) Reset() {
	*x = RunInput{}
	mi := &file_gish_plugin_v1_command_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunInput) ProtoMessage() {}

func (x *RunInput) ProtoReflect() protoreflect.Message {
	mi := &file_gish_plugin_v1_command_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunInput.ProtoReflect.Descriptor instead.
func (*RunInput) Descriptor() ([]byte, []int) {
	return file_gish_plugin_v1_command_proto_rawDescGZIP(), []int{3}
}

func (x *RunInput) GetInput() isRunInput_Input {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *RunInput) GetStart() *RunStart {
	if x != nil {
		if x, ok := x.Input.(*RunInput_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *RunInput) GetStdin() []byte {
	if x != nil {
		if x, ok := x.Input.(*RunInput_Stdin); ok {
			return x.Stdin
		}
	}
	return nil
}

func (x *RunInput) GetStdinEof() bool {
	if x != nil {
		if x, ok := x.Input.(*RunInput_StdinEof); ok {
			return x.StdinEof
		}
	}
	return false
}

type isRunInput_Input interface {
	isRunInput_Input()
}

type RunInput_Start struct {
	Start *RunStart `protobuf:"bytes,1,opt,name=start,proto3,oneof"`
}

type RunInput_Stdin struct {
	Stdin []byte `protobuf:"bytes,2,opt,name=stdin,proto3,oneof"`
}

type RunInput_StdinEof struct {
	StdinEof bool `protobuf:"varint,3,opt,name=stdin_eof,json=stdinEof,proto3,oneof"`
}

func (*RunInput_Start) isRunInput_Input() {}

func (*RunInput_Stdin) isRunInput_Input() {}

func (*RunInput_StdinEof) isRunInput_Input() {}

type RunStart struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Args  []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	Cwd   string                 `protobuf:"bytes,3,opt,name=cwd,proto3" json:"cwd,omitempty"`
	// Allowlisted environment, per the filtered-env invariant.
	Env           map[string]string `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunStart) Reset() {
	*x = RunStart{}
	mi := &file_gish_plugin_v1_command_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunStart) ProtoMessage() {}

func (x *RunStart) ProtoReflect() protoreflect.Message {
	mi := &file_gish_plugin_v1_command_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunStart.ProtoReflect.Descriptor instead.
func (*RunStart) Descriptor() ([]byte, []int) {
	return file_gish_plugin_v1_command_proto_rawDescGZIP(), []int{4}
}

func (x *RunStart) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RunStart) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *RunStart) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *RunStart) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

type RunOutput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Output:
	//
	//	*RunOutput_Stdout
	//	*RunOutput_Stderr
	//	*RunOutput_Exit
	Output        isRunOutput_Output `protobuf_oneof:"output"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunOutput) Reset() {
	*x = RunOutput{}
	mi := &file_gish_plugin_v1_command_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunOutput) ProtoMessage() {}

func (x *RunOutput) ProtoReflect() protoreflect.Message {
	mi := &file_gish_plugin_v1_command_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunOutput.ProtoReflect.Descriptor instead.
func (*RunOutput) Descriptor() ([]byte, []int) {
	return file_gish_plugin_v1_command_proto_rawDescGZIP(), []int{5}
}

func (x *RunOutput) GetOutput() isRunOutput_Output {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *RunOutput) GetStdout() []byte {
	if x != nil {
		if x, ok := x.Output.(*RunOutput_Stdout); ok {
			return x.Stdout
		}
	}
	return nil
}

func (x *RunOutput) GetStderr() []byte {
	if x != nil {
		if x, ok := x.Output.(*RunOutput_Stderr); ok {
			return x.Stderr
		}
	}
	return nil
}

func (x *RunOutput) GetExit() int32 {
	if x != nil {
		if x, ok := x.Output.(*RunOutput_Exit); ok {
			return x.Exit
		}
	}
	return 0
}

type isRunOutput_Output interface {
	isRunOutput_Output()
}

type RunOutput_Stdout struct {
	Stdout []byte `protobuf:"bytes,1,opt,name=stdout,proto3,oneof"`
}

type RunOutput_Stderr struct {
	Stderr []byte `protobuf:"bytes,2,opt,name=stderr,proto3,oneof"`
}

type RunOutput_Exit struct {
	// Final message: the command's exit status.
	Exit int32 `protobuf:"varint,3,opt,name=exit,proto3,oneof"`
}

func (*RunOutput_Stdout) isRunOutput_Output() {}

func (*RunOutput_Stderr) isRunOutput_Output() {}

func (*RunOutput_Exit) isRunOutput_Output() {}

var File_gish_plugin_v1_command_proto protoreflect.FileDescriptor

const file_gish_plugin_v1_command_proto_rawDesc = "" +
	"\n" +
	"\x1cgish/plugin/v1/command.proto\x12\x0egish.plugin.v1\"\x11\n" +
	"\x0fCommandsRequest\";\n" +
	"\vCommandSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\asummary\x18\x02 \x01(\tR\asummary\"K\n" +
	"\x10CommandsResponse\x127\n" +
	"\bcommands\x18\x01 \x03(\v2\x1b.gish.plugin.v1.CommandSpecR\bcommands\"|\n" +
	"\bRunInput\x120\n" +
	"\x05start\x18\x01 \x01(\v2\x18.gish.plugin.v1.RunStartH\x00R\x05start\x12\x16\n" +
	"\x05stdin\x18\x02 \x01(\fH\x00R\x05stdin\x12\x1d\n" +
	"\tstdin_eof\x18\x03 \x01(\bH\x00R\bstdinEofB\a\n" +
	"\x05input\"\xb1\x01\n" +
	"\bRunStart\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\x12\x10\n" +
	"\x03cwd\x18\x03 \x01(\tR\x03cwd\x123\n" +
	"\x03env\x18\x04 \x03(\v2!.gish.plugin.v1.RunStart.EnvEntryR\x03env\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"_\n" +
	"\tRunOutput\x12\x18\n" +
	"\x06stdout\x18\x01 \x01(\fH\x00R\x06stdout\x12\x18\n" +
	"\x06stderr\x18\x02 \x01(\fH\x00R\x06stderr\x12\x14\n" +
	"\x04exit\x18\x03 \x01(\x05H\x00R\x04exitB\b\n" +
	"\x06output2\xa0\x01\n" +
	"\x0fCommandProvider\x12M\n" +
	"\bCommands\x12\x1f.gish.plugin.v1.CommandsRequest\x1a .gish.plugin.v1.CommandsResponse\x12>\n" +
	"\x03Run\x12\x18.gish.plugin.v1.RunInput\x1a\x19.gish.plugin.v1.RunOutput(\x010\x01B2Z0github.com/blairham/gish/pkg/pluginapi;pluginapib\x06proto3"

var (
	file_gish_plugin_v1_command_proto_rawDescOnce sync.Once
	file_gish_plugin_v1_command_proto_rawDescData []byte
)

func file_gish_plugin_v1_command_proto_rawDescGZIP() []byte {
	file_gish_plugin_v1_command_proto_rawDescOnce.Do(func() {
		file_gish_plugin_v1_command_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gish_plugin_v1_command_proto_rawDesc), len(file_gish_plugin_v1_command_proto_rawDesc)))
	})
	return file_gish_plugin_v1_command_proto_rawDescData
}

var file_gish_plugin_v1_command_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_gish_plugin_v1_command_proto_goTypes = []any{
	(*CommandsRequest)(nil),  // 0: gish.plugin.v1.CommandsRequest
	(*CommandSpec)(nil),      // 1: gish.plugin.v1.CommandSpec
	(*CommandsResponse)(nil), // 2: gish.plugin.v1.CommandsResponse
	(*RunInput)(nil),         // 3: gish.plugin.v1.RunInput
	(*RunStart)(nil),         // 4: gish.plugin.v1.RunStart
	(*RunOutput)(nil),        // 5: gish.plugin.v1.RunOutput
	nil,                      // 6: gish.plugin.v1.RunStart.EnvEntry
}
var file_gish_plugin_v1_command_proto_depIdxs = []int32{
	1, // 0: gish.plugin.v1.CommandsResponse.commands:type_name -> gish.plugin.v1.CommandSpec
	4, // 1: gish.plugin.v1.RunInput.start:type_name -> gish.plugin.v1.RunStart
	6, // 2: gish.plugin.v1.RunStart.env:type_name -> gish.plugin.v1.RunStart.EnvEntry
	0, // 3: gish.plugin.v1.CommandProvider.Commands:input_type -> gish.plugin.v1.CommandsRequest
	3, // 4: gish.plugin.v1.CommandProvider.Run:input_type -> gish.plugin.v1.RunInput
	2, // 5: gish.plugin.v1.CommandProvider.Commands:output_type -> gish.plugin.v1.CommandsResponse
	5, // 6: gish.plugin.v1.CommandProvider.Run:output_type -> gish.plugin.v1.RunOutput
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_gish_plugin_v1_command_proto_init() }
func file_gish_plugin_v1_command_proto_init() {
	if File_gish_plugin_v1_command_proto != nil {
		return
	}
	file_gish_plugin_v1_command_proto_msgTypes[3].OneofWrappers = []any{
		(*RunInput_Start)(nil),
		(*RunInput_Stdin)(nil),
		(*RunInput_StdinEof)(nil),
	}
	file_gish_plugin_v1_command_proto_msgTypes[5].OneofWrappers = []any{
		(*RunOutput_Stdout)(nil),
		(*RunOutput_Stderr)(nil),
		(*RunOutput_Exit)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gish_plugin_v1_command_proto_rawDesc), len(file_gish_plugin_v1_command_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gish_plugin_v1_command_proto_goTypes,
		DependencyIndexes: file_gish_plugin_v1_command_proto_depIdxs,
		MessageInfos:      file_gish_plugin_v1_command_proto_msgTypes,
	}.Build()
	File_gish_plugin_v1_command_proto = out.File
	file_gish_plugin_v1_command_proto_goTypes = nil
	file_gish_plugin_v1_command_proto_depIdxs = nil
}
