// Tier-2 native plugin API — shared types and the discovery service.
//
// Gish plugins are resident subprocesses speaking gRPC via
// hashicorp/go-plugin. The host launches a plugin lazily on first use,
// performs the go-plugin handshake (see internal/pluginhost), then calls
// Describe once to learn which capability services the plugin serves on
// the same connection. A plugin may implement any subset.
//
// Contract rules (the reason this tier exists):
//   - This protobuf surface is versioned: breaking changes mean a new
//     gish.plugin.v2 package, never an edit to v1.
//   - Every host→plugin call carries a deadline. A plugin that misses it
//     is skipped for that interaction, not waited on — a slow plugin must
//     never block a keystroke or a prompt.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: gish/plugin/v1/common.proto

package pluginapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Capability names the services a plugin implements.
type Capability int32

const (
	Capability_CAPABILITY_UNSPECIFIED    Capability = 0
	Capability_CAPABILITY_COMPLETION     Capability = 1 // CompletionProvider
	Capability_CAPABILITY_PROMPT_SEGMENT Capability = 2 // PromptSegmentProvider
	Capability_CAPABILITY_HISTORY        Capability = 3 // HistoryBackend
	Capability_CAPABILITY_COMMAND        Capability = 4 // CommandProvider (#11)
)

// Enum value maps for Capability.
var (
	Capability_name = map[int32]string{
		0: "CAPABILITY_UNSPECIFIED",
		1: "CAPABILITY_COMPLETION",
		2: "CAPABILITY_PROMPT_SEGMENT",
		3: "CAPABILITY_HISTORY",
		4: "CAPABILITY_COMMAND",
	}
	Capability_value = map[string]int32{
		"CAPABILITY_UNSPECIFIED":    0,
		"CAPABILITY_COMPLETION":     1,
		"CAPABILITY_PROMPT_SEGMENT": 2,
		"CAPABILITY_HISTORY":        3,
		"CAPABILITY_COMMAND":        4,
	}
)

func (x Capability) Enum() *Capability {
	p := new(Capability)
	*p = x
	return p
}

func (x Capability) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Capability) Descriptor() protoreflect.EnumDescriptor {
	return file_gish_plugin_v1_common_proto_enumTypes[0].Descriptor()
}

func (Capability) Type() protoreflect.EnumType {
	return &file_gish_plugin_v1_common_proto_enumTypes[0]
}

func (x Capability) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Capability.Descriptor instead.
func (Capability) EnumDescriptor() ([]byte, []int) {
	return file_gish_plugin_v1_common_proto_rawDescGZIP(), []int{0}
}

type DescribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeRequest) Reset() {
	*x = DescribeRequest{}
	mi := &file_gish_plugin_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeRequest) ProtoMessage() {}

func (x *DescribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gish_plugin_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeRequest.ProtoReflect.Descriptor instead.
func (*DescribeRequest) Descriptor() ([]byte, []int) {
	return file_gish_plugin_v1_common_proto_rawDescGZIP(), []int{0}
}

type DescribeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Machine name, unique per plugin (e.g. "git-prompt"). Used in
	// configuration and diagnostics.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Plugin's own version string, informational only.
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// Which capability services this plugin serves.
	Capabilities  []Capability `protobuf:"varint,3,rep,packed,name=capabilities,proto3,enum=gish.plugin.v1.Capability" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeResponse) Reset() {
	*x = DescribeResponse{}
	mi := &file_gish_plugin_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeResponse) ProtoMessage() {}

func (x *DescribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gish_plugin_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeResponse.ProtoReflect.Descriptor instead.
func (*DescribeResponse) Descriptor() ([]byte, []int) {
	return file_gish_plugin_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *DescribeResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DescribeResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *DescribeResponse) GetCapabilities() []Capability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

var File_gish_plugin_v1_common_proto protoreflect.FileDescriptor

const file_gish_plugin_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x1bgish/plugin/v1/common.proto\x12\x0egish.plugin.v1\"\x11\n" +
	"\x0fDescribeRequest\"\x80\x01\n" +
	"\x10DescribeResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12>\n" +
	"\fcapabilities\x18\x03 \x03(\x0e2\x1a.gish.plugin.v1.CapabilityR\fcapabilities*\x92\x01\n" +
	"\n" +
	"Capability\x12\x1a\n" +
	"\x16CAPABILITY_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15CAPABILITY_COMPLETION\x10\x01\x12\x1d\n" +
	"\x19CAPABILITY_PROMPT_SEGMENT\x10\x02\x12\x16\n" +
	"\x12CAPABILITY_HISTORY\x10\x03\x12\x16\n" +
	"\x12CAPABILITY_COMMAND\x10\x042[\n" +
	"\n" +
	"PluginInfo\x12M\n" +
	"\bDescribe\x12\x1f.gish.plugin.v1.DescribeRequest\x1a .gish.plugin.v1.DescribeResponseB2Z0github.com/blairham/gish/pkg/pluginapi;pluginapib\x06proto3"

var (
	file_gish_plugin_v1_common_proto_rawDescOnce sync.Once
	file_gish_plugin_v1_common_proto_rawDescData []byte
)

func file_gish_plugin_v1_common_proto_rawDescGZIP() []byte {
	file_gish_plugin_v1_common_proto_rawDescOnce.Do(func() {
		file_gish_plugin_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gish_plugin_v1_common_proto_rawDesc), len(file_gish_plugin_v1_common_proto_rawDesc)))
	})
	return file_gish_plugin_v1_common_proto_rawDescData
}

var file_gish_plugin_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_gish_plugin_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gish_plugin_v1_common_proto_goTypes = []any{
	(Capability)(0),          // 0: gish.plugin.v1.Capability
	(*DescribeRequest)(nil),  // 1: gish.plugin.v1.DescribeRequest
	(*DescribeResponse)(nil), // 2: gish.plugin.v1.DescribeResponse
}
var file_gish_plugin_v1_common_proto_depIdxs = []int32{
	0, // 0: gish.plugin.v1.DescribeResponse.capabilities:type_name -> gish.plugin.v1.Capability
	1, // 1: gish.plugin.v1.PluginInfo.Describe:input_type -> gish.plugin.v1.DescribeRequest
	2, // 2: gish.plugin.v1.PluginInfo.Describe:output_type -> gish.plugin.v1.DescribeResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_gish_plugin_v1_common_proto_init() }
func file_gish_plugin_v1_common_proto_init() {
	if File_gish_plugin_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gish_plugin_v1_common_proto_rawDesc), len(file_gish_plugin_v1_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gish_plugin_v1_common_proto_goTypes,
		DependencyIndexes: file_gish_plugin_v1_common_proto_depIdxs,
		EnumInfos:         file_gish_plugin_v1_common_proto_enumTypes,
		MessageInfos:      file_gish_plugin_v1_common_proto_msgTypes,
	}.Build()
	File_gish_plugin_v1_common_proto = out.File
	file_gish_plugin_v1_common_proto_goTypes = nil
	file_gish_plugin_v1_common_proto_depIdxs = nil
}
