// CompletionProvider — tab-completion candidates from a resident plugin.
//
// Modeled on the carapace/LSP experience: the shell sends the current
// buffer and cursor, the plugin streams candidate batches back so the UI
// can render early results while a slow source (an API, a large repo)
// keeps working. The host imposes a per-keystroke deadline; batches that
// arrive after it are dropped, not queued.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.35.1
// source: swash/plugin/v1/completion.proto

package pluginapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CompletionProvider_Complete_FullMethodName = "/swash.plugin.v1.CompletionProvider/Complete"
)

// CompletionProviderClient is the client API for CompletionProvider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CompletionProviderClient interface {
	// Complete returns candidate batches for the buffer/cursor in the
	// request. The final batch sets final=true; the host may cancel the
	// stream at any time (deadline, or the user kept typing).
	Complete(ctx context.Context, in *CompleteRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CompleteBatch], error)
}

type completionProviderClient struct {
	cc grpc.ClientConnInterface
}

func NewCompletionProviderClient(cc grpc.ClientConnInterface) CompletionProviderClient {
	return &completionProviderClient{cc}
}

func (c *completionProviderClient) Complete(ctx context.Context, in *CompleteRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CompleteBatch], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CompletionProvider_ServiceDesc.Streams[0], CompletionProvider_Complete_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CompleteRequest, CompleteBatch]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CompletionProvider_CompleteClient = grpc.ServerStreamingClient[CompleteBatch]

// CompletionProviderServer is the server API for CompletionProvider service.
// All implementations must embed UnimplementedCompletionProviderServer
// for forward compatibility.
type CompletionProviderServer interface {
	// Complete returns candidate batches for the buffer/cursor in the
	// request. The final batch sets final=true; the host may cancel the
	// stream at any time (deadline, or the user kept typing).
	Complete(*CompleteRequest, grpc.ServerStreamingServer[CompleteBatch]) error
	mustEmbedUnimplementedCompletionProviderServer()
}

// UnimplementedCompletionProviderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCompletionProviderServer struct{}

func (UnimplementedCompletionProviderServer) Complete(*CompleteRequest, grpc.ServerStreamingServer[CompleteBatch]) error {
	return status.Error(codes.Unimplemented, "method Complete not implemented")
}
func (UnimplementedCompletionProviderServer) mustEmbedUnimplementedCompletionProviderServer() {}
func (UnimplementedCompletionProviderServer) testEmbeddedByValue()                            {}

// UnsafeCompletionProviderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CompletionProviderServer will
// result in compilation errors.
type UnsafeCompletionProviderServer interface {
	mustEmbedUnimplementedCompletionProviderServer()
}

func RegisterCompletionProviderServer(s grpc.ServiceRegistrar, srv CompletionProviderServer) {
	// If the following call panics, it indicates UnimplementedCompletionProviderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CompletionProvider_ServiceDesc, srv)
}

func _CompletionProvider_Complete_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CompleteRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CompletionProviderServer).Complete(m, &grpc.GenericServerStream[CompleteRequest, CompleteBatch]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CompletionProvider_CompleteServer = grpc.ServerStreamingServer[CompleteBatch]

// CompletionProvider_ServiceDesc is the grpc.ServiceDesc for CompletionProvider service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CompletionProvider_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "swash.plugin.v1.CompletionProvider",
	HandlerType: (*CompletionProviderServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Complete",
			Handler:       _CompletionProvider_Complete_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "swash/plugin/v1/completion.proto",
}
