// EnvProvider — direnv-class per-directory environment diffs (#12).
//
// On directory change the host asks env plugins for a diff. The trust
// model is the contract's core, enforced host-side:
//
//   - Nothing ever applies silently. A proposed diff applies only after
//     the user runs `trust allow`, which records (plugin, for_dir,
//     diff-hash). Any change to the proposal — a different hash —
//     re-pends and re-prompts, direnv's edit-reprompts semantics.
//   - A deny-list of variables no plugin may set (loader hooks like
//     LD_PRELOAD/DYLD_*, IFS, shell-internal GISH_*) is stripped
//     host-side before a diff is even proposed. PATH is settable, but
//     only ever through the visible allow flow above.
//   - Requests carry the allowlisted env subset, never the full
//     environment (the filtered-env invariant).
//
// Budget: EnvDiff is bounded (100ms default). A miss skips the diff for
// this prompt and retries on the next one — the prompt never waits.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: gish/plugin/v1/env.proto

package pluginapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EnvProvider_EnvDiff_FullMethodName = "/gish.plugin.v1.EnvProvider/EnvDiff"
	EnvProvider_Allow_FullMethodName   = "/gish.plugin.v1.EnvProvider/Allow"
)

// EnvProviderClient is the client API for EnvProvider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EnvProviderClient interface {
	// EnvDiff proposes environment changes for a directory. An empty
	// response (no for_dir) means the plugin has nothing for this cwd.
	EnvDiff(ctx context.Context, in *EnvDiffRequest, opts ...grpc.CallOption) (*EnvDiffResponse, error)
	// Allow tells the plugin the user approved this directory, so a
	// plugin wrapping a tool with its *own* approval model can satisfy it
	// in the same gesture (#137).
	//
	// The motivating case is direnv: it has `direnv allow`, and gish has
	// the trust flow above. Prompting twice for one action is
	// unacceptable, and letting the wrapped tool's prompt replace gish's
	// would give up the host-enforced guarantees. So `trust allow` calls
	// this first, then re-asks for the diff.
	//
	// Optional: a plugin with no second trust model returns unimplemented
	// (or an empty response) and the host carries on. Never called
	// without an explicit user approval — this is not a way to
	// pre-authorize anything.
	Allow(ctx context.Context, in *AllowRequest, opts ...grpc.CallOption) (*AllowResponse, error)
}

type envProviderClient struct {
	cc grpc.ClientConnInterface
}

func NewEnvProviderClient(cc grpc.ClientConnInterface) EnvProviderClient {
	return &envProviderClient{cc}
}

func (c *envProviderClient) EnvDiff(ctx context.Context, in *EnvDiffRequest, opts ...grpc.CallOption) (*EnvDiffResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnvDiffResponse)
	err := c.cc.Invoke(ctx, EnvProvider_EnvDiff_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *envProviderClient) Allow(ctx context.Context, in *AllowRequest, opts ...grpc.CallOption) (*AllowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AllowResponse)
	err := c.cc.Invoke(ctx, EnvProvider_Allow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EnvProviderServer is the server API for EnvProvider service.
// All implementations must embed UnimplementedEnvProviderServer
// for forward compatibility.
type EnvProviderServer interface {
	// EnvDiff proposes environment changes for a directory. An empty
	// response (no for_dir) means the plugin has nothing for this cwd.
	EnvDiff(context.Context, *EnvDiffRequest) (*EnvDiffResponse, error)
	// Allow tells the plugin the user approved this directory, so a
	// plugin wrapping a tool with its *own* approval model can satisfy it
	// in the same gesture (#137).
	//
	// The motivating case is direnv: it has `direnv allow`, and gish has
	// the trust flow above. Prompting twice for one action is
	// unacceptable, and letting the wrapped tool's prompt replace gish's
	// would give up the host-enforced guarantees. So `trust allow` calls
	// this first, then re-asks for the diff.
	//
	// Optional: a plugin with no second trust model returns unimplemented
	// (or an empty response) and the host carries on. Never called
	// without an explicit user approval — this is not a way to
	// pre-authorize anything.
	Allow(context.Context, *AllowRequest) (*AllowResponse, error)
	mustEmbedUnimplementedEnvProviderServer()
}

// UnimplementedEnvProviderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEnvProviderServer struct{}

func (UnimplementedEnvProviderServer) EnvDiff(context.Context, *EnvDiffRequest) (*EnvDiffResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnvDiff not implemented")
}
func (UnimplementedEnvProviderServer) Allow(context.Context, *AllowRequest) (*AllowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Allow not implemented")
}
func (UnimplementedEnvProviderServer) mustEmbedUnimplementedEnvProviderServer() {}
func (UnimplementedEnvProviderServer) testEmbeddedByValue()                     {}

// UnsafeEnvProviderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EnvProviderServer will
// result in compilation errors.
type UnsafeEnvProviderServer interface {
	mustEmbedUnimplementedEnvProviderServer()
}

func RegisterEnvProviderServer(s grpc.ServiceRegistrar, srv EnvProviderServer) {
	// If the following call panics, it indicates UnimplementedEnvProviderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EnvProvider_ServiceDesc, srv)
}

func _EnvProvider_EnvDiff_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnvDiffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnvProviderServer).EnvDiff(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnvProvider_EnvDiff_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnvProviderServer).EnvDiff(ctx, req.(*EnvDiffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnvProvider_Allow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnvProviderServer).Allow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnvProvider_Allow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnvProviderServer).Allow(ctx, req.(*AllowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EnvProvider_ServiceDesc is the grpc.ServiceDesc for EnvProvider service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EnvProvider_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gish.plugin.v1.EnvProvider",
	HandlerType: (*EnvProviderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EnvDiff",
			Handler:    _EnvProvider_EnvDiff_Handler,
		},
		{
			MethodName: "Allow",
			Handler:    _EnvProvider_Allow_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gish/plugin/v1/env.proto",
}
