// HistoryBackend — pluggable history storage and search.
//
// The shell keeps its own local history file regardless; a HistoryBackend
// plugin observes appends and can serve richer search (sync across
// machines, dedupe, secret-scrubbing, fuzzy/frecency ranking). Append is
// fire-and-forget from the shell's perspective — a slow backend must
// never delay accepting the next command.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: swash/plugin/v1/history.proto

package pluginapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HistoryEntry struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Command string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	// Wall-clock start, milliseconds since the Unix epoch (host-stamped).
	StartedUnixMs int64  `protobuf:"varint,2,opt,name=started_unix_ms,json=startedUnixMs,proto3" json:"started_unix_ms,omitempty"`
	DurationMs    int64  `protobuf:"varint,3,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	ExitCode      int32  `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Cwd           string `protobuf:"bytes,5,opt,name=cwd,proto3" json:"cwd,omitempty"`
	// Opaque per-session id, stable for the life of one interactive shell.
	SessionId     string `protobuf:"bytes,6,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryEntry) Reset() {
	*x = HistoryEntry{}
	mi := &file_swash_plugin_v1_history_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryEntry) ProtoMessage() {}

func (x *HistoryEntry) ProtoReflect() protoreflect.Message {
	mi := &file_swash_plugin_v1_history_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryEntry.ProtoReflect.Descriptor instead.
func (*HistoryEntry) Descriptor() ([]byte, []int) {
	return file_swash_plugin_v1_history_proto_rawDescGZIP(), []int{0}
}

func (x *HistoryEntry) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *HistoryEntry) GetStartedUnixMs() int64 {
	if x != nil {
		return x.StartedUnixMs
	}
	return 0
}

func (x *HistoryEntry) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *HistoryEntry) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *HistoryEntry) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *HistoryEntry) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type AppendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         *HistoryEntry          `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendRequest) Reset() {
	*x = AppendRequest{}
	mi := &file_swash_plugin_v1_history_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendRequest) ProtoMessage() {}

func (x *AppendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swash_plugin_v1_history_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendRequest.ProtoReflect.Descriptor instead.
func (*AppendRequest) Descriptor() ([]byte, []int) {
	return file_swash_plugin_v1_history_proto_rawDescGZIP(), []int{1}
}

func (x *AppendRequest) GetEntry() *HistoryEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

type AppendResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// False lets a backend decline an entry (e.g. its own ignore rules);
	// the shell's local history is unaffected either way.
	Stored        bool `protobuf:"varint,1,opt,name=stored,proto3" json:"stored,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendResponse) Reset() {
	*x = AppendResponse{}
	mi := &file_swash_plugin_v1_history_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendResponse) ProtoMessage() {}

func (x *AppendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swash_plugin_v1_history_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendResponse.ProtoReflect.Descriptor instead.
func (*AppendResponse) Descriptor() ([]byte, []int) {
	return file_swash_plugin_v1_history_proto_rawDescGZIP(), []int{2}
}

func (x *AppendResponse) GetStored() bool {
	if x != nil {
		return x.Stored
	}
	return false
}

type SearchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Query string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	// Current directory, for backends that rank by locality.
	Cwd   string `protobuf:"bytes,2,opt,name=cwd,proto3" json:"cwd,omitempty"`
	Limit uint32 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	// True restricts matching to command prefixes (up-arrow style);
	// false is full fuzzy search (ctrl-r style).
	PrefixOnly    bool `protobuf:"varint,4,opt,name=prefix_only,json=prefixOnly,proto3" json:"prefix_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_swash_plugin_v1_history_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swash_plugin_v1_history_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_swash_plugin_v1_history_proto_rawDescGZIP(), []int{3}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *SearchRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchRequest) GetPrefixOnly() bool {
	if x != nil {
		return x.PrefixOnly
	}
	return false
}

type SearchBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*HistoryEntry        `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	Final         bool                   `protobuf:"varint,2,opt,name=final,proto3" json:"final,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchBatch) Reset() {
	*x = SearchBatch{}
	mi := &file_swash_plugin_v1_history_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchBatch) ProtoMessage() {}

func (x *SearchBatch) ProtoReflect() protoreflect.Message {
	mi := &file_swash_plugin_v1_history_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchBatch.ProtoReflect.Descriptor instead.
func (*SearchBatch) Descriptor() ([]byte, []int) {
	return file_swash_plugin_v1_history_proto_rawDescGZIP(), []int{4}
}

func (x *SearchBatch) GetEntries() []*HistoryEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *SearchBatch) GetFinal() bool {
	if x != nil {
		return x.Final
	}
	return false
}

var File_swash_plugin_v1_history_proto protoreflect.FileDescriptor

const file_swash_plugin_v1_history_proto_rawDesc = "" +
	"\n" +
	"\x1dswash/plugin/v1/history.proto\x12\x0fswash.plugin.v1\"\xbf\x01\n" +
	"\fHistoryEntry\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12&\n" +
	"\x0fstarted_unix_ms\x18\x02 \x01(\x03R\rstartedUnixMs\x12\x1f\n" +
	"\vduration_ms\x18\x03 \x01(\x03R\n" +
	"durationMs\x12\x1b\n" +
	"\texit_code\x18\x04 \x01(\x05R\bexitCode\x12\x10\n" +
	"\x03cwd\x18\x05 \x01(\tR\x03cwd\x12\x1d\n" +
	"\n" +
	"session_id\x18\x06 \x01(\tR\tsessionId\"D\n" +
	"\rAppendRequest\x123\n" +
	"\x05entry\x18\x01 \x01(\v2\x1d.swash.plugin.v1.HistoryEntryR\x05entry\"(\n" +
	"\x0eAppendResponse\x12\x16\n" +
	"\x06stored\x18\x01 \x01(\bR\x06stored\"n\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x10\n" +
	"\x03cwd\x18\x02 \x01(\tR\x03cwd\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\x12\x1f\n" +
	"\vprefix_only\x18\x04 \x01(\bR\n" +
	"prefixOnly\"\\\n" +
	"\vSearchBatch\x127\n" +
	"\aentries\x18\x01 \x03(\v2\x1d.swash.plugin.v1.HistoryEntryR\aentries\x12\x14\n" +
	"\x05final\x18\x02 \x01(\bR\x05final2\xa5\x01\n" +
	"\x0eHistoryBackend\x12I\n" +
	"\x06Append\x12\x1e.swash.plugin.v1.AppendRequest\x1a\x1f.swash.plugin.v1.AppendResponse\x12H\n" +
	"\x06Search\x12\x1e.swash.plugin.v1.SearchRequest\x1a\x1c.swash.plugin.v1.SearchBatch0\x01B3Z1github.com/blairham/swash/pkg/pluginapi;pluginapib\x06proto3"

var (
	file_swash_plugin_v1_history_proto_rawDescOnce sync.Once
	file_swash_plugin_v1_history_proto_rawDescData []byte
)

func file_swash_plugin_v1_history_proto_rawDescGZIP() []byte {
	file_swash_plugin_v1_history_proto_rawDescOnce.Do(func() {
		file_swash_plugin_v1_history_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_swash_plugin_v1_history_proto_rawDesc), len(file_swash_plugin_v1_history_proto_rawDesc)))
	})
	return file_swash_plugin_v1_history_proto_rawDescData
}

var file_swash_plugin_v1_history_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_swash_plugin_v1_history_proto_goTypes = []any{
	(*HistoryEntry)(nil),   // 0: swash.plugin.v1.HistoryEntry
	(*AppendRequest)(nil),  // 1: swash.plugin.v1.AppendRequest
	(*AppendResponse)(nil), // 2: swash.plugin.v1.AppendResponse
	(*SearchRequest)(nil),  // 3: swash.plugin.v1.SearchRequest
	(*SearchBatch)(nil),    // 4: swash.plugin.v1.SearchBatch
}
var file_swash_plugin_v1_history_proto_depIdxs = []int32{
	0, // 0: swash.plugin.v1.AppendRequest.entry:type_name -> swash.plugin.v1.HistoryEntry
	0, // 1: swash.plugin.v1.SearchBatch.entries:type_name -> swash.plugin.v1.HistoryEntry
	1, // 2: swash.plugin.v1.HistoryBackend.Append:input_type -> swash.plugin.v1.AppendRequest
	3, // 3: swash.plugin.v1.HistoryBackend.Search:input_type -> swash.plugin.v1.SearchRequest
	2, // 4: swash.plugin.v1.HistoryBackend.Append:output_type -> swash.plugin.v1.AppendResponse
	4, // 5: swash.plugin.v1.HistoryBackend.Search:output_type -> swash.plugin.v1.SearchBatch
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_swash_plugin_v1_history_proto_init() }
func file_swash_plugin_v1_history_proto_init() {
	if File_swash_plugin_v1_history_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_swash_plugin_v1_history_proto_rawDesc), len(file_swash_plugin_v1_history_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_swash_plugin_v1_history_proto_goTypes,
		DependencyIndexes: file_swash_plugin_v1_history_proto_depIdxs,
		MessageInfos:      file_swash_plugin_v1_history_proto_msgTypes,
	}.Build()
	File_swash_plugin_v1_history_proto = out.File
	file_swash_plugin_v1_history_proto_goTypes = nil
	file_swash_plugin_v1_history_proto_depIdxs = nil
}
