// HistoryBackend — pluggable history storage and search.
//
// The shell keeps its own local history file regardless; a HistoryBackend
// plugin observes appends and can serve richer search (sync across
// machines, dedupe, secret-scrubbing, fuzzy/frecency ranking). Append is
// fire-and-forget from the shell's perspective — a slow backend must
// never delay accepting the next command.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.35.1
// source: swash/plugin/v1/history.proto

package pluginapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HistoryBackend_Append_FullMethodName = "/swash.plugin.v1.HistoryBackend/Append"
	HistoryBackend_Search_FullMethodName = "/swash.plugin.v1.HistoryBackend/Search"
)

// HistoryBackendClient is the client API for HistoryBackend service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HistoryBackendClient interface {
	// Append records an executed command. Called after the command exits.
	Append(ctx context.Context, in *AppendRequest, opts ...grpc.CallOption) (*AppendResponse, error)
	// Search streams matches, best first, in batches.
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SearchBatch], error)
}

type historyBackendClient struct {
	cc grpc.ClientConnInterface
}

func NewHistoryBackendClient(cc grpc.ClientConnInterface) HistoryBackendClient {
	return &historyBackendClient{cc}
}

func (c *historyBackendClient) Append(ctx context.Context, in *AppendRequest, opts ...grpc.CallOption) (*AppendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppendResponse)
	err := c.cc.Invoke(ctx, HistoryBackend_Append_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historyBackendClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SearchBatch], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HistoryBackend_ServiceDesc.Streams[0], HistoryBackend_Search_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SearchRequest, SearchBatch]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HistoryBackend_SearchClient = grpc.ServerStreamingClient[SearchBatch]

// HistoryBackendServer is the server API for HistoryBackend service.
// All implementations must embed UnimplementedHistoryBackendServer
// for forward compatibility.
type HistoryBackendServer interface {
	// Append records an executed command. Called after the command exits.
	Append(context.Context, *AppendRequest) (*AppendResponse, error)
	// Search streams matches, best first, in batches.
	Search(*SearchRequest, grpc.ServerStreamingServer[SearchBatch]) error
	mustEmbedUnimplementedHistoryBackendServer()
}

// UnimplementedHistoryBackendServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHistoryBackendServer struct{}

func (UnimplementedHistoryBackendServer) Append(context.Context, *AppendRequest) (*AppendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Append not implemented")
}
func (UnimplementedHistoryBackendServer) Search(*SearchRequest, grpc.ServerStreamingServer[SearchBatch]) error {
	return status.Error(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedHistoryBackendServer) mustEmbedUnimplementedHistoryBackendServer() {}
func (UnimplementedHistoryBackendServer) testEmbeddedByValue()                        {}

// UnsafeHistoryBackendServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HistoryBackendServer will
// result in compilation errors.
type UnsafeHistoryBackendServer interface {
	mustEmbedUnimplementedHistoryBackendServer()
}

func RegisterHistoryBackendServer(s grpc.ServiceRegistrar, srv HistoryBackendServer) {
	// If the following call panics, it indicates UnimplementedHistoryBackendServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HistoryBackend_ServiceDesc, srv)
}

func _HistoryBackend_Append_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoryBackendServer).Append(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HistoryBackend_Append_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoryBackendServer).Append(ctx, req.(*AppendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HistoryBackend_Search_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SearchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HistoryBackendServer).Search(m, &grpc.GenericServerStream[SearchRequest, SearchBatch]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HistoryBackend_SearchServer = grpc.ServerStreamingServer[SearchBatch]

// HistoryBackend_ServiceDesc is the grpc.ServiceDesc for HistoryBackend service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HistoryBackend_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "swash.plugin.v1.HistoryBackend",
	HandlerType: (*HistoryBackendServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Append",
			Handler:    _HistoryBackend_Append_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Search",
			Handler:       _HistoryBackend_Search_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "swash/plugin/v1/history.proto",
}
