// ThemeProvider — whole-prompt themes from a resident plugin (#30).
//
// The third replacement tier for the prompt: where PromptSegmentProvider
// contributes one segment to the built-in layout, a ThemeProvider renders
// the *entire* prompt set (prompt, continuation, right prompt) per read.
// starship is the reference external implementation of this shape; this
// service is its native gRPC flavor.
//
// Contract: RenderPrompt is budget-bounded exactly like segments — the
// host derives a deadline from the theme's declared budget (default
// 50ms) and on a miss reuses the theme's previous prompt set or falls
// back to the built-in theme. The prompt never waits.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: gish/plugin/v1/theme.proto

package pluginapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ThemeProvider_Themes_FullMethodName       = "/gish.plugin.v1.ThemeProvider/Themes"
	ThemeProvider_RenderPrompt_FullMethodName = "/gish.plugin.v1.ThemeProvider/RenderPrompt"
)

// ThemeProviderClient is the client API for ThemeProvider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ThemeProviderClient interface {
	// Themes enumerates the theme names this plugin offers; GISH_THEME
	// selects by name. Called once after Describe.
	Themes(ctx context.Context, in *ThemesRequest, opts ...grpc.CallOption) (*ThemesResponse, error)
	// RenderPrompt produces the full prompt set for one read.
	RenderPrompt(ctx context.Context, in *RenderPromptRequest, opts ...grpc.CallOption) (*RenderPromptResponse, error)
}

type themeProviderClient struct {
	cc grpc.ClientConnInterface
}

func NewThemeProviderClient(cc grpc.ClientConnInterface) ThemeProviderClient {
	return &themeProviderClient{cc}
}

func (c *themeProviderClient) Themes(ctx context.Context, in *ThemesRequest, opts ...grpc.CallOption) (*ThemesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ThemesResponse)
	err := c.cc.Invoke(ctx, ThemeProvider_Themes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *themeProviderClient) RenderPrompt(ctx context.Context, in *RenderPromptRequest, opts ...grpc.CallOption) (*RenderPromptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenderPromptResponse)
	err := c.cc.Invoke(ctx, ThemeProvider_RenderPrompt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ThemeProviderServer is the server API for ThemeProvider service.
// All implementations must embed UnimplementedThemeProviderServer
// for forward compatibility.
type ThemeProviderServer interface {
	// Themes enumerates the theme names this plugin offers; GISH_THEME
	// selects by name. Called once after Describe.
	Themes(context.Context, *ThemesRequest) (*ThemesResponse, error)
	// RenderPrompt produces the full prompt set for one read.
	RenderPrompt(context.Context, *RenderPromptRequest) (*RenderPromptResponse, error)
	mustEmbedUnimplementedThemeProviderServer()
}

// UnimplementedThemeProviderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedThemeProviderServer struct{}

func (UnimplementedThemeProviderServer) Themes(context.Context, *ThemesRequest) (*ThemesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Themes not implemented")
}
func (UnimplementedThemeProviderServer) RenderPrompt(context.Context, *RenderPromptRequest) (*RenderPromptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RenderPrompt not implemented")
}
func (UnimplementedThemeProviderServer) mustEmbedUnimplementedThemeProviderServer() {}
func (UnimplementedThemeProviderServer) testEmbeddedByValue()                       {}

// UnsafeThemeProviderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ThemeProviderServer will
// result in compilation errors.
type UnsafeThemeProviderServer interface {
	mustEmbedUnimplementedThemeProviderServer()
}

func RegisterThemeProviderServer(s grpc.ServiceRegistrar, srv ThemeProviderServer) {
	// If the following call panics, it indicates UnimplementedThemeProviderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ThemeProvider_ServiceDesc, srv)
}

func _ThemeProvider_Themes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ThemesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThemeProviderServer).Themes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThemeProvider_Themes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThemeProviderServer).Themes(ctx, req.(*ThemesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ThemeProvider_RenderPrompt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenderPromptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThemeProviderServer).RenderPrompt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThemeProvider_RenderPrompt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThemeProviderServer).RenderPrompt(ctx, req.(*RenderPromptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ThemeProvider_ServiceDesc is the grpc.ServiceDesc for ThemeProvider service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ThemeProvider_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gish.plugin.v1.ThemeProvider",
	HandlerType: (*ThemeProviderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Themes",
			Handler:    _ThemeProvider_Themes_Handler,
		},
		{
			MethodName: "RenderPrompt",
			Handler:    _ThemeProvider_RenderPrompt_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gish/plugin/v1/theme.proto",
}
