// CommandProvider — plugins registering shell commands over gRPC (#11):
// the cloudctl pattern applied to a shell. A registered command runs
// like a builtin: dispatched by name before PATH lookup, with its I/O
// streamed over the connection.
//
// Precedence rules (decided on #11): interpreter and gish-native builtin
// names are reserved — claims on them are rejected. Shell functions
// shadow plugin commands (the user always wins). Plugin commands shadow
// PATH binaries, like functions do. Between plugins, the
// lexicographically first plugin name wins a contested command.
//
// v1 streams stdin/stdout/stderr; there is no raw-terminal handover —
// full-screen commands are out of scope until a PTY-passing design
// exists. Execution starts at Enter (never the keystroke path), so Run
// carries no latency budget; cancellation rides the command context.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: koi/plugin/v1/command.proto

package pluginapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CommandProvider_Commands_FullMethodName = "/koi.plugin.v1.CommandProvider/Commands"
	CommandProvider_Run_FullMethodName      = "/koi.plugin.v1.CommandProvider/Run"
)

// CommandProviderClient is the client API for CommandProvider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CommandProviderClient interface {
	// Commands enumerates what this plugin provides. Called after
	// Describe, and its result may be cached against the plugin binary's
	// mtime — keep it deterministic.
	Commands(ctx context.Context, in *CommandsRequest, opts ...grpc.CallOption) (*CommandsResponse, error)
	// Run executes one invocation. The first client message must be
	// start; stdin chunks follow as the command consumes them. The server
	// streams stdout/stderr chunks and ends with exit.
	Run(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RunInput, RunOutput], error)
}

type commandProviderClient struct {
	cc grpc.ClientConnInterface
}

func NewCommandProviderClient(cc grpc.ClientConnInterface) CommandProviderClient {
	return &commandProviderClient{cc}
}

func (c *commandProviderClient) Commands(ctx context.Context, in *CommandsRequest, opts ...grpc.CallOption) (*CommandsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandsResponse)
	err := c.cc.Invoke(ctx, CommandProvider_Commands_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commandProviderClient) Run(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RunInput, RunOutput], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CommandProvider_ServiceDesc.Streams[0], CommandProvider_Run_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RunInput, RunOutput]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CommandProvider_RunClient = grpc.BidiStreamingClient[RunInput, RunOutput]

// CommandProviderServer is the server API for CommandProvider service.
// All implementations must embed UnimplementedCommandProviderServer
// for forward compatibility.
type CommandProviderServer interface {
	// Commands enumerates what this plugin provides. Called after
	// Describe, and its result may be cached against the plugin binary's
	// mtime — keep it deterministic.
	Commands(context.Context, *CommandsRequest) (*CommandsResponse, error)
	// Run executes one invocation. The first client message must be
	// start; stdin chunks follow as the command consumes them. The server
	// streams stdout/stderr chunks and ends with exit.
	Run(grpc.BidiStreamingServer[RunInput, RunOutput]) error
	mustEmbedUnimplementedCommandProviderServer()
}

// UnimplementedCommandProviderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCommandProviderServer struct{}

func (UnimplementedCommandProviderServer) Commands(context.Context, *CommandsRequest) (*CommandsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Commands not implemented")
}
func (UnimplementedCommandProviderServer) Run(grpc.BidiStreamingServer[RunInput, RunOutput]) error {
	return status.Error(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedCommandProviderServer) mustEmbedUnimplementedCommandProviderServer() {}
func (UnimplementedCommandProviderServer) testEmbeddedByValue()                         {}

// UnsafeCommandProviderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommandProviderServer will
// result in compilation errors.
type UnsafeCommandProviderServer interface {
	mustEmbedUnimplementedCommandProviderServer()
}

func RegisterCommandProviderServer(s grpc.ServiceRegistrar, srv CommandProviderServer) {
	// If the following call panics, it indicates UnimplementedCommandProviderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CommandProvider_ServiceDesc, srv)
}

func _CommandProvider_Commands_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandProviderServer).Commands(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommandProvider_Commands_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandProviderServer).Commands(ctx, req.(*CommandsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommandProvider_Run_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CommandProviderServer).Run(&grpc.GenericServerStream[RunInput, RunOutput]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CommandProvider_RunServer = grpc.BidiStreamingServer[RunInput, RunOutput]

// CommandProvider_ServiceDesc is the grpc.ServiceDesc for CommandProvider service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CommandProvider_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "koi.plugin.v1.CommandProvider",
	HandlerType: (*CommandProviderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Commands",
			Handler:    _CommandProvider_Commands_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Run",
			Handler:       _CommandProvider_Run_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "koi/plugin/v1/command.proto",
}
