// Tier-2 native plugin API — shared types and the discovery service.
//
// Gish plugins are resident subprocesses speaking gRPC via
// hashicorp/go-plugin. The host launches a plugin lazily on first use,
// performs the go-plugin handshake (see internal/pluginhost), then calls
// Describe once to learn which capability services the plugin serves on
// the same connection. A plugin may implement any subset.
//
// Contract rules (the reason this tier exists):
//   - This protobuf surface is versioned: breaking changes mean a new
//     gish.plugin.v2 package, never an edit to v1.
//   - Every host→plugin call carries a deadline. A plugin that misses it
//     is skipped for that interaction, not waited on — a slow plugin must
//     never block a keystroke or a prompt.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: gish/plugin/v1/common.proto

package pluginapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PluginInfo_Describe_FullMethodName = "/gish.plugin.v1.PluginInfo/Describe"
)

// PluginInfoClient is the client API for PluginInfo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PluginInfo is the one service every plugin must implement.
type PluginInfoClient interface {
	// Describe is called once per plugin process, immediately after the
	// go-plugin handshake succeeds.
	Describe(ctx context.Context, in *DescribeRequest, opts ...grpc.CallOption) (*DescribeResponse, error)
}

type pluginInfoClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginInfoClient(cc grpc.ClientConnInterface) PluginInfoClient {
	return &pluginInfoClient{cc}
}

func (c *pluginInfoClient) Describe(ctx context.Context, in *DescribeRequest, opts ...grpc.CallOption) (*DescribeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DescribeResponse)
	err := c.cc.Invoke(ctx, PluginInfo_Describe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginInfoServer is the server API for PluginInfo service.
// All implementations must embed UnimplementedPluginInfoServer
// for forward compatibility.
//
// PluginInfo is the one service every plugin must implement.
type PluginInfoServer interface {
	// Describe is called once per plugin process, immediately after the
	// go-plugin handshake succeeds.
	Describe(context.Context, *DescribeRequest) (*DescribeResponse, error)
	mustEmbedUnimplementedPluginInfoServer()
}

// UnimplementedPluginInfoServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPluginInfoServer struct{}

func (UnimplementedPluginInfoServer) Describe(context.Context, *DescribeRequest) (*DescribeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Describe not implemented")
}
func (UnimplementedPluginInfoServer) mustEmbedUnimplementedPluginInfoServer() {}
func (UnimplementedPluginInfoServer) testEmbeddedByValue()                    {}

// UnsafePluginInfoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginInfoServer will
// result in compilation errors.
type UnsafePluginInfoServer interface {
	mustEmbedUnimplementedPluginInfoServer()
}

func RegisterPluginInfoServer(s grpc.ServiceRegistrar, srv PluginInfoServer) {
	// If the following call panics, it indicates UnimplementedPluginInfoServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PluginInfo_ServiceDesc, srv)
}

func _PluginInfo_Describe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginInfoServer).Describe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginInfo_Describe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginInfoServer).Describe(ctx, req.(*DescribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PluginInfo_ServiceDesc is the grpc.ServiceDesc for PluginInfo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PluginInfo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gish.plugin.v1.PluginInfo",
	HandlerType: (*PluginInfoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Describe",
			Handler:    _PluginInfo_Describe_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gish/plugin/v1/common.proto",
}
