// CompletionProvider — tab-completion candidates from a resident plugin.
//
// Modeled on the carapace/LSP experience: the shell sends the current
// buffer and cursor, the plugin streams candidate batches back so the UI
// can render early results while a slow source (an API, a large repo)
// keeps working. The host imposes a per-keystroke deadline; batches that
// arrive after it are dropped, not queued.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: gish/plugin/v1/completion.proto

package pluginapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CompleteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Full command-line buffer, UTF-8.
	Line string `protobuf:"bytes,1,opt,name=line,proto3" json:"line,omitempty"`
	// Byte offset of the cursor within line.
	Cursor uint32 `protobuf:"varint,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	// Working directory of the interactive session.
	Cwd string `protobuf:"bytes,3,opt,name=cwd,proto3" json:"cwd,omitempty"`
	// Filtered environment. The host sends an allowlisted subset, never
	// the full environment — plugins should not see secrets by default.
	Env map[string]string `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Upper bound the host will render; plugins should stop early.
	MaxCandidates uint32 `protobuf:"varint,5,opt,name=max_candidates,json=maxCandidates,proto3" json:"max_candidates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteRequest) Reset() {
	*x = CompleteRequest{}
	mi := &file_gish_plugin_v1_completion_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteRequest) ProtoMessage() {}

func (x *CompleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gish_plugin_v1_completion_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteRequest.ProtoReflect.Descriptor instead.
func (*CompleteRequest) Descriptor() ([]byte, []int) {
	return file_gish_plugin_v1_completion_proto_rawDescGZIP(), []int{0}
}

func (x *CompleteRequest) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

func (x *CompleteRequest) GetCursor() uint32 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *CompleteRequest) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *CompleteRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *CompleteRequest) GetMaxCandidates() uint32 {
	if x != nil {
		return x.MaxCandidates
	}
	return 0
}

type Candidate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Text inserted into the buffer when selected.
	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	// Menu display text; defaults to value when empty.
	Display string `protobuf:"bytes,2,opt,name=display,proto3" json:"display,omitempty"`
	// One-line description shown next to the candidate.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Relative ranking hint, higher sorts first. Host merges candidates
	// from multiple providers by score, then provider priority.
	Score         uint32 `protobuf:"varint,4,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Candidate) Reset() {
	*x = Candidate{}
	mi := &file_gish_plugin_v1_completion_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Candidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Candidate) ProtoMessage() {}

func (x *Candidate) ProtoReflect() protoreflect.Message {
	mi := &file_gish_plugin_v1_completion_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Candidate.ProtoReflect.Descriptor instead.
func (*Candidate) Descriptor() ([]byte, []int) {
	return file_gish_plugin_v1_completion_proto_rawDescGZIP(), []int{1}
}

func (x *Candidate) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Candidate) GetDisplay() string {
	if x != nil {
		return x.Display
	}
	return ""
}

func (x *Candidate) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Candidate) GetScore() uint32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type CompleteBatch struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Candidates []*Candidate           `protobuf:"bytes,1,rep,name=candidates,proto3" json:"candidates,omitempty"`
	// True on the last batch; lets the host distinguish "done" from
	// "stream cut by deadline".
	Final         bool `protobuf:"varint,2,opt,name=final,proto3" json:"final,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteBatch) Reset() {
	*x = CompleteBatch{}
	mi := &file_gish_plugin_v1_completion_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteBatch) ProtoMessage() {}

func (x *CompleteBatch) ProtoReflect() protoreflect.Message {
	mi := &file_gish_plugin_v1_completion_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteBatch.ProtoReflect.Descriptor instead.
func (*CompleteBatch) Descriptor() ([]byte, []int) {
	return file_gish_plugin_v1_completion_proto_rawDescGZIP(), []int{2}
}

func (x *CompleteBatch) GetCandidates() []*Candidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

func (x *CompleteBatch) GetFinal() bool {
	if x != nil {
		return x.Final
	}
	return false
}

var File_gish_plugin_v1_completion_proto protoreflect.FileDescriptor

const file_gish_plugin_v1_completion_proto_rawDesc = "" +
	"\n" +
	"\x1fgish/plugin/v1/completion.proto\x12\x0egish.plugin.v1\"\xea\x01\n" +
	"\x0fCompleteRequest\x12\x12\n" +
	"\x04line\x18\x01 \x01(\tR\x04line\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\rR\x06cursor\x12\x10\n" +
	"\x03cwd\x18\x03 \x01(\tR\x03cwd\x12:\n" +
	"\x03env\x18\x04 \x03(\v2(.gish.plugin.v1.CompleteRequest.EnvEntryR\x03env\x12%\n" +
	"\x0emax_candidates\x18\x05 \x01(\rR\rmaxCandidates\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"s\n" +
	"\tCandidate\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x18\n" +
	"\adisplay\x18\x02 \x01(\tR\adisplay\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05score\x18\x04 \x01(\rR\x05score\"`\n" +
	"\rCompleteBatch\x129\n" +
	"\n" +
	"candidates\x18\x01 \x03(\v2\x19.gish.plugin.v1.CandidateR\n" +
	"candidates\x12\x14\n" +
	"\x05final\x18\x02 \x01(\bR\x05final2b\n" +
	"\x12CompletionProvider\x12L\n" +
	"\bComplete\x12\x1f.gish.plugin.v1.CompleteRequest\x1a\x1d.gish.plugin.v1.CompleteBatch0\x01B5Z3github.com/blairham/gish/pkg/pluginapi/v1;pluginapib\x06proto3"

var (
	file_gish_plugin_v1_completion_proto_rawDescOnce sync.Once
	file_gish_plugin_v1_completion_proto_rawDescData []byte
)

func file_gish_plugin_v1_completion_proto_rawDescGZIP() []byte {
	file_gish_plugin_v1_completion_proto_rawDescOnce.Do(func() {
		file_gish_plugin_v1_completion_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gish_plugin_v1_completion_proto_rawDesc), len(file_gish_plugin_v1_completion_proto_rawDesc)))
	})
	return file_gish_plugin_v1_completion_proto_rawDescData
}

var file_gish_plugin_v1_completion_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_gish_plugin_v1_completion_proto_goTypes = []any{
	(*CompleteRequest)(nil), // 0: gish.plugin.v1.CompleteRequest
	(*Candidate)(nil),       // 1: gish.plugin.v1.Candidate
	(*CompleteBatch)(nil),   // 2: gish.plugin.v1.CompleteBatch
	nil,                     // 3: gish.plugin.v1.CompleteRequest.EnvEntry
}
var file_gish_plugin_v1_completion_proto_depIdxs = []int32{
	3, // 0: gish.plugin.v1.CompleteRequest.env:type_name -> gish.plugin.v1.CompleteRequest.EnvEntry
	1, // 1: gish.plugin.v1.CompleteBatch.candidates:type_name -> gish.plugin.v1.Candidate
	0, // 2: gish.plugin.v1.CompletionProvider.Complete:input_type -> gish.plugin.v1.CompleteRequest
	2, // 3: gish.plugin.v1.CompletionProvider.Complete:output_type -> gish.plugin.v1.CompleteBatch
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_gish_plugin_v1_completion_proto_init() }
func file_gish_plugin_v1_completion_proto_init() {
	if File_gish_plugin_v1_completion_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gish_plugin_v1_completion_proto_rawDesc), len(file_gish_plugin_v1_completion_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gish_plugin_v1_completion_proto_goTypes,
		DependencyIndexes: file_gish_plugin_v1_completion_proto_depIdxs,
		MessageInfos:      file_gish_plugin_v1_completion_proto_msgTypes,
	}.Build()
	File_gish_plugin_v1_completion_proto = out.File
	file_gish_plugin_v1_completion_proto_goTypes = nil
	file_gish_plugin_v1_completion_proto_depIdxs = nil
}
