// EnvProvider — direnv-class per-directory environment diffs (#12).
//
// On directory change the host asks env plugins for a diff. The trust
// model is the contract's core, enforced host-side:
//
//   - Nothing ever applies silently. A proposed diff applies only after
//     the user runs `trust allow`, which records (plugin, for_dir,
//     diff-hash). Any change to the proposal — a different hash —
//     re-pends and re-prompts, direnv's edit-reprompts semantics.
//   - A deny-list of variables no plugin may set (loader hooks like
//     LD_PRELOAD/DYLD_*, IFS, shell-internal GISH_*) is stripped
//     host-side before a diff is even proposed. PATH is settable, but
//     only ever through the visible allow flow above.
//   - Requests carry the allowlisted env subset, never the full
//     environment (the filtered-env invariant).
//
// Budget: EnvDiff is bounded (100ms default). A miss skips the diff for
// this prompt and retries on the next one — the prompt never waits.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: gish/plugin/v1/env.proto

package pluginapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnvDiffRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Directory just entered.
	Cwd string `protobuf:"bytes,1,opt,name=cwd,proto3" json:"cwd,omitempty"`
	// Filtered environment. The host sends an allowlisted subset, never
	// the full environment — env plugins do not see secrets by default.
	Env map[string]string `protobuf:"bytes,2,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Monotonic per-session sequence number; lets plugins drop stale
	// requests that were superseded before they were served.
	EventSeq      uint64 `protobuf:"varint,3,opt,name=event_seq,json=eventSeq,proto3" json:"event_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvDiffRequest) Reset() {
	*x = EnvDiffRequest{}
	mi := &file_gish_plugin_v1_env_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvDiffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvDiffRequest) ProtoMessage() {}

func (x *EnvDiffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gish_plugin_v1_env_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvDiffRequest.ProtoReflect.Descriptor instead.
func (*EnvDiffRequest) Descriptor() ([]byte, []int) {
	return file_gish_plugin_v1_env_proto_rawDescGZIP(), []int{0}
}

func (x *EnvDiffRequest) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *EnvDiffRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *EnvDiffRequest) GetEventSeq() uint64 {
	if x != nil {
		return x.EventSeq
	}
	return 0
}

type EnvDiffResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Directory this diff derives from (e.g. where the .envrc-equivalent
	// lives). Must be cwd or an ancestor of it — anything else is
	// discarded. Trust is keyed on it, and the diff stays applied for
	// any cwd underneath it until the shell leaves that subtree.
	ForDir string `protobuf:"bytes,1,opt,name=for_dir,json=forDir,proto3" json:"for_dir,omitempty"`
	// Variables to set (name → value). Deny-listed names are stripped by
	// the host.
	Set map[string]string `protobuf:"bytes,2,rep,name=set,proto3" json:"set,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Variables to unset. Same deny-list applies.
	Unset         []string `protobuf:"bytes,3,rep,name=unset,proto3" json:"unset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvDiffResponse) Reset() {
	*x = EnvDiffResponse{}
	mi := &file_gish_plugin_v1_env_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvDiffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvDiffResponse) ProtoMessage() {}

func (x *EnvDiffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gish_plugin_v1_env_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvDiffResponse.ProtoReflect.Descriptor instead.
func (*EnvDiffResponse) Descriptor() ([]byte, []int) {
	return file_gish_plugin_v1_env_proto_rawDescGZIP(), []int{1}
}

func (x *EnvDiffResponse) GetForDir() string {
	if x != nil {
		return x.ForDir
	}
	return ""
}

func (x *EnvDiffResponse) GetSet() map[string]string {
	if x != nil {
		return x.Set
	}
	return nil
}

func (x *EnvDiffResponse) GetUnset() []string {
	if x != nil {
		return x.Unset
	}
	return nil
}

type AllowRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The directory the user approved — the for_dir of the diff they were
	// shown, never an arbitrary path.
	ForDir string `protobuf:"bytes,1,opt,name=for_dir,json=forDir,proto3" json:"for_dir,omitempty"`
	// Same filtered environment EnvDiffRequest carries.
	Env           map[string]string `protobuf:"bytes,2,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllowRequest) Reset() {
	*x = AllowRequest{}
	mi := &file_gish_plugin_v1_env_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllowRequest) ProtoMessage() {}

func (x *AllowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gish_plugin_v1_env_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllowRequest.ProtoReflect.Descriptor instead.
func (*AllowRequest) Descriptor() ([]byte, []int) {
	return file_gish_plugin_v1_env_proto_rawDescGZIP(), []int{2}
}

func (x *AllowRequest) GetForDir() string {
	if x != nil {
		return x.ForDir
	}
	return ""
}

func (x *AllowRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

type AllowResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// False means the plugin could not record the approval (the wrapped
	// tool failed, or is missing). The host still applies the diff it
	// showed — gish's own trust record is authoritative for gish — but it
	// says so, because the next shell may see the proposal again.
	Recorded bool `protobuf:"varint,1,opt,name=recorded,proto3" json:"recorded,omitempty"`
	// Optional one-line explanation for the user when recorded is false.
	Detail        string `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllowResponse) Reset() {
	*x = AllowResponse{}
	mi := &file_gish_plugin_v1_env_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllowResponse) ProtoMessage() {}

func (x *AllowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gish_plugin_v1_env_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllowResponse.ProtoReflect.Descriptor instead.
func (*AllowResponse) Descriptor() ([]byte, []int) {
	return file_gish_plugin_v1_env_proto_rawDescGZIP(), []int{3}
}

func (x *AllowResponse) GetRecorded() bool {
	if x != nil {
		return x.Recorded
	}
	return false
}

func (x *AllowResponse) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

var File_gish_plugin_v1_env_proto protoreflect.FileDescriptor

const file_gish_plugin_v1_env_proto_rawDesc = "" +
	"\n" +
	"\x18gish/plugin/v1/env.proto\x12\x0egish.plugin.v1\"\xb2\x01\n" +
	"\x0eEnvDiffRequest\x12\x10\n" +
	"\x03cwd\x18\x01 \x01(\tR\x03cwd\x129\n" +
	"\x03env\x18\x02 \x03(\v2'.gish.plugin.v1.EnvDiffRequest.EnvEntryR\x03env\x12\x1b\n" +
	"\tevent_seq\x18\x03 \x01(\x04R\beventSeq\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb4\x01\n" +
	"\x0fEnvDiffResponse\x12\x17\n" +
	"\afor_dir\x18\x01 \x01(\tR\x06forDir\x12:\n" +
	"\x03set\x18\x02 \x03(\v2(.gish.plugin.v1.EnvDiffResponse.SetEntryR\x03set\x12\x14\n" +
	"\x05unset\x18\x03 \x03(\tR\x05unset\x1a6\n" +
	"\bSetEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x98\x01\n" +
	"\fAllowRequest\x12\x17\n" +
	"\afor_dir\x18\x01 \x01(\tR\x06forDir\x127\n" +
	"\x03env\x18\x02 \x03(\v2%.gish.plugin.v1.AllowRequest.EnvEntryR\x03env\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"C\n" +
	"\rAllowResponse\x12\x1a\n" +
	"\brecorded\x18\x01 \x01(\bR\brecorded\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail2\x9f\x01\n" +
	"\vEnvProvider\x12J\n" +
	"\aEnvDiff\x12\x1e.gish.plugin.v1.EnvDiffRequest\x1a\x1f.gish.plugin.v1.EnvDiffResponse\x12D\n" +
	"\x05Allow\x12\x1c.gish.plugin.v1.AllowRequest\x1a\x1d.gish.plugin.v1.AllowResponseB5Z3github.com/blairham/gish/pkg/pluginapi/v1;pluginapib\x06proto3"

var (
	file_gish_plugin_v1_env_proto_rawDescOnce sync.Once
	file_gish_plugin_v1_env_proto_rawDescData []byte
)

func file_gish_plugin_v1_env_proto_rawDescGZIP() []byte {
	file_gish_plugin_v1_env_proto_rawDescOnce.Do(func() {
		file_gish_plugin_v1_env_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gish_plugin_v1_env_proto_rawDesc), len(file_gish_plugin_v1_env_proto_rawDesc)))
	})
	return file_gish_plugin_v1_env_proto_rawDescData
}

var file_gish_plugin_v1_env_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_gish_plugin_v1_env_proto_goTypes = []any{
	(*EnvDiffRequest)(nil),  // 0: gish.plugin.v1.EnvDiffRequest
	(*EnvDiffResponse)(nil), // 1: gish.plugin.v1.EnvDiffResponse
	(*AllowRequest)(nil),    // 2: gish.plugin.v1.AllowRequest
	(*AllowResponse)(nil),   // 3: gish.plugin.v1.AllowResponse
	nil,                     // 4: gish.plugin.v1.EnvDiffRequest.EnvEntry
	nil,                     // 5: gish.plugin.v1.EnvDiffResponse.SetEntry
	nil,                     // 6: gish.plugin.v1.AllowRequest.EnvEntry
}
var file_gish_plugin_v1_env_proto_depIdxs = []int32{
	4, // 0: gish.plugin.v1.EnvDiffRequest.env:type_name -> gish.plugin.v1.EnvDiffRequest.EnvEntry
	5, // 1: gish.plugin.v1.EnvDiffResponse.set:type_name -> gish.plugin.v1.EnvDiffResponse.SetEntry
	6, // 2: gish.plugin.v1.AllowRequest.env:type_name -> gish.plugin.v1.AllowRequest.EnvEntry
	0, // 3: gish.plugin.v1.EnvProvider.EnvDiff:input_type -> gish.plugin.v1.EnvDiffRequest
	2, // 4: gish.plugin.v1.EnvProvider.Allow:input_type -> gish.plugin.v1.AllowRequest
	1, // 5: gish.plugin.v1.EnvProvider.EnvDiff:output_type -> gish.plugin.v1.EnvDiffResponse
	3, // 6: gish.plugin.v1.EnvProvider.Allow:output_type -> gish.plugin.v1.AllowResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_gish_plugin_v1_env_proto_init() }
func file_gish_plugin_v1_env_proto_init() {
	if File_gish_plugin_v1_env_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gish_plugin_v1_env_proto_rawDesc), len(file_gish_plugin_v1_env_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gish_plugin_v1_env_proto_goTypes,
		DependencyIndexes: file_gish_plugin_v1_env_proto_depIdxs,
		MessageInfos:      file_gish_plugin_v1_env_proto_msgTypes,
	}.Build()
	File_gish_plugin_v1_env_proto = out.File
	file_gish_plugin_v1_env_proto_goTypes = nil
	file_gish_plugin_v1_env_proto_depIdxs = nil
}
