// ShellEvents — event-triggered automations (#83).
//
// The host streams session events to subscribed plugins, which may
// respond with *proposals*. The contract is defined here before any
// host wiring exists, which is the same order the rest of this package
// was built in: the shape of a plugin contract is much harder to change
// after plugins exist than before.
//
// **Status: contract only. The host does not serve this yet.** A plugin
// implementing it today will simply never be subscribed.
//
// Three rules, none of which are negotiable, and all of which are
// inherited rather than invented:
//
//   - **No exec channel, ever.** A plugin proposes; the shell decides.
//     This is the #111 line — koi hosts other people's agents rather
//     than being one — and it is why orchestration cannot move behind
//     the plugin boundary. Every proposal that leads to running
//     something goes through the same preview-and-approve surfaces as
//     #20 and #34: it lands in the editor buffer, or it is gated, and it
//     never runs on its own.
//   - **The host never blocks on a subscriber.** Events are
//     fire-and-forget into a bounded buffer, drop-oldest. A plugin that
//     stops reading loses events; it does not slow the prompt down. The
//     same deadline posture as every other call in this package.
//   - **Events carry allowlisted, scrub-safe data only.** A command name
//     and its exit status, not the full command line; the allowlisted
//     env subset, not the environment. The #10/#12/#20 posture applies
//     unchanged — an event stream is a new place for a secret to leak,
//     so it is designed not to carry one.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: koi/plugin/v1/events.proto

package pluginapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EventKind is what happened. Additive: an unknown kind must be ignored
// by plugins rather than treated as an error, so the host can add kinds
// without breaking anything already in the wild.
type EventKind int32

const (
	EventKind_EVENT_KIND_UNSPECIFIED EventKind = 0
	// The shell changed directory.
	EventKind_EVENT_KIND_DIR_CHANGE EventKind = 1
	// A command finished. Carries the command *name* and status, never
	// the full line — see the scrub-safety rule.
	EventKind_EVENT_KIND_COMMAND_DONE EventKind = 2
	// A watched file changed. Only paths a plugin asked to watch.
	EventKind_EVENT_KIND_FILE_CHANGE EventKind = 3
	// The session is ending; a last chance to flush state.
	EventKind_EVENT_KIND_SESSION_END EventKind = 4
)

// Enum value maps for EventKind.
var (
	EventKind_name = map[int32]string{
		0: "EVENT_KIND_UNSPECIFIED",
		1: "EVENT_KIND_DIR_CHANGE",
		2: "EVENT_KIND_COMMAND_DONE",
		3: "EVENT_KIND_FILE_CHANGE",
		4: "EVENT_KIND_SESSION_END",
	}
	EventKind_value = map[string]int32{
		"EVENT_KIND_UNSPECIFIED":  0,
		"EVENT_KIND_DIR_CHANGE":   1,
		"EVENT_KIND_COMMAND_DONE": 2,
		"EVENT_KIND_FILE_CHANGE":  3,
		"EVENT_KIND_SESSION_END":  4,
	}
)

func (x EventKind) Enum() *EventKind {
	p := new(EventKind)
	*p = x
	return p
}

func (x EventKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventKind) Descriptor() protoreflect.EnumDescriptor {
	return file_koi_plugin_v1_events_proto_enumTypes[0].Descriptor()
}

func (EventKind) Type() protoreflect.EnumType {
	return &file_koi_plugin_v1_events_proto_enumTypes[0]
}

func (x EventKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventKind.Descriptor instead.
func (EventKind) EnumDescriptor() ([]byte, []int) {
	return file_koi_plugin_v1_events_proto_rawDescGZIP(), []int{0}
}

type ShellEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Kind  EventKind              `protobuf:"varint,1,opt,name=kind,proto3,enum=koi.plugin.v1.EventKind" json:"kind,omitempty"`
	// Monotonic per-session sequence number. Same discipline as every
	// other request here: a subscriber that falls behind can tell, and a
	// proposal answering a superseded event can be dropped by the host.
	EventSeq uint64 `protobuf:"varint,2,opt,name=event_seq,json=eventSeq,proto3" json:"event_seq,omitempty"`
	// Current working directory.
	Cwd string `protobuf:"bytes,3,opt,name=cwd,proto3" json:"cwd,omitempty"`
	// Wall-clock, milliseconds since the Unix epoch (host-stamped).
	UnixMs int64 `protobuf:"varint,4,opt,name=unix_ms,json=unixMs,proto3" json:"unix_ms,omitempty"`
	// Allowlisted environment subset. Never the full environment.
	Env map[string]string `protobuf:"bytes,5,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// COMMAND_DONE only: the command's first word — `git`, not
	// `git push --force origin main`. The argument list is where secrets
	// and paths live, and a plugin reacting to "a git command failed"
	// does not need them.
	CommandName string `protobuf:"bytes,6,opt,name=command_name,json=commandName,proto3" json:"command_name,omitempty"`
	// COMMAND_DONE only: its exit status.
	ExitCode int32 `protobuf:"varint,7,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	// COMMAND_DONE only: how long it ran.
	DurationMs int64 `protobuf:"varint,8,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	// FILE_CHANGE only: the path that changed.
	Path          string `protobuf:"bytes,9,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellEvent) Reset() {
	*x = ShellEvent{}
	mi := &file_koi_plugin_v1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellEvent) ProtoMessage() {}

func (x *ShellEvent) ProtoReflect() protoreflect.Message {
	mi := &file_koi_plugin_v1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellEvent.ProtoReflect.Descriptor instead.
func (*ShellEvent) Descriptor() ([]byte, []int) {
	return file_koi_plugin_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *ShellEvent) GetKind() EventKind {
	if x != nil {
		return x.Kind
	}
	return EventKind_EVENT_KIND_UNSPECIFIED
}

func (x *ShellEvent) GetEventSeq() uint64 {
	if x != nil {
		return x.EventSeq
	}
	return 0
}

func (x *ShellEvent) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *ShellEvent) GetUnixMs() int64 {
	if x != nil {
		return x.UnixMs
	}
	return 0
}

func (x *ShellEvent) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ShellEvent) GetCommandName() string {
	if x != nil {
		return x.CommandName
	}
	return ""
}

func (x *ShellEvent) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ShellEvent) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *ShellEvent) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// Proposal is what a plugin may send back. Every field is something the
// user sees before anything happens; there is deliberately no field
// that causes execution.
type Proposal struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The event this responds to, so the host can drop a proposal that
	// answers a superseded event (a suggestion for the directory you just
	// left is worse than no suggestion).
	EventSeq uint64 `protobuf:"varint,1,opt,name=event_seq,json=eventSeq,proto3" json:"event_seq,omitempty"`
	// A one-line notice to show. Advisory, never blocking.
	Notice string `protobuf:"bytes,2,opt,name=notice,proto3" json:"notice,omitempty"`
	// A command to *offer*. It lands in the editor buffer for the user to
	// read, edit, and run — the #20 posture — and never executes on its
	// own. The host owns quoting; this is data, not buffer text.
	SuggestedCommand string `protobuf:"bytes,3,opt,name=suggested_command,json=suggestedCommand,proto3" json:"suggested_command,omitempty"`
	// Why the plugin is suggesting it. A suggestion the user cannot
	// evaluate is one they will either blindly accept or permanently
	// ignore, and both are bad outcomes.
	Rationale string `protobuf:"bytes,4,opt,name=rationale,proto3" json:"rationale,omitempty"`
	// Paths the plugin wants FILE_CHANGE events for, relative to cwd or
	// absolute. Declared here rather than in a separate RPC so a plugin
	// can adjust what it watches as it learns where it is.
	WatchPaths    []string `protobuf:"bytes,5,rep,name=watch_paths,json=watchPaths,proto3" json:"watch_paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Proposal) Reset() {
	*x = Proposal{}
	mi := &file_koi_plugin_v1_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Proposal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Proposal) ProtoMessage() {}

func (x *Proposal) ProtoReflect() protoreflect.Message {
	mi := &file_koi_plugin_v1_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Proposal.ProtoReflect.Descriptor instead.
func (*Proposal) Descriptor() ([]byte, []int) {
	return file_koi_plugin_v1_events_proto_rawDescGZIP(), []int{1}
}

func (x *Proposal) GetEventSeq() uint64 {
	if x != nil {
		return x.EventSeq
	}
	return 0
}

func (x *Proposal) GetNotice() string {
	if x != nil {
		return x.Notice
	}
	return ""
}

func (x *Proposal) GetSuggestedCommand() string {
	if x != nil {
		return x.SuggestedCommand
	}
	return ""
}

func (x *Proposal) GetRationale() string {
	if x != nil {
		return x.Rationale
	}
	return ""
}

func (x *Proposal) GetWatchPaths() []string {
	if x != nil {
		return x.WatchPaths
	}
	return nil
}

var File_koi_plugin_v1_events_proto protoreflect.FileDescriptor

const file_koi_plugin_v1_events_proto_rawDesc = "" +
	"\n" +
	"\x1akoi/plugin/v1/events.proto\x12\rkoi.plugin.v1\"\xe5\x02\n" +
	"\n" +
	"ShellEvent\x12,\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x18.koi.plugin.v1.EventKindR\x04kind\x12\x1b\n" +
	"\tevent_seq\x18\x02 \x01(\x04R\beventSeq\x12\x10\n" +
	"\x03cwd\x18\x03 \x01(\tR\x03cwd\x12\x17\n" +
	"\aunix_ms\x18\x04 \x01(\x03R\x06unixMs\x124\n" +
	"\x03env\x18\x05 \x03(\v2\".koi.plugin.v1.ShellEvent.EnvEntryR\x03env\x12!\n" +
	"\fcommand_name\x18\x06 \x01(\tR\vcommandName\x12\x1b\n" +
	"\texit_code\x18\a \x01(\x05R\bexitCode\x12\x1f\n" +
	"\vduration_ms\x18\b \x01(\x03R\n" +
	"durationMs\x12\x12\n" +
	"\x04path\x18\t \x01(\tR\x04path\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xab\x01\n" +
	"\bProposal\x12\x1b\n" +
	"\tevent_seq\x18\x01 \x01(\x04R\beventSeq\x12\x16\n" +
	"\x06notice\x18\x02 \x01(\tR\x06notice\x12+\n" +
	"\x11suggested_command\x18\x03 \x01(\tR\x10suggestedCommand\x12\x1c\n" +
	"\trationale\x18\x04 \x01(\tR\trationale\x12\x1f\n" +
	"\vwatch_paths\x18\x05 \x03(\tR\n" +
	"watchPaths*\x97\x01\n" +
	"\tEventKind\x12\x1a\n" +
	"\x16EVENT_KIND_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15EVENT_KIND_DIR_CHANGE\x10\x01\x12\x1b\n" +
	"\x17EVENT_KIND_COMMAND_DONE\x10\x02\x12\x1a\n" +
	"\x16EVENT_KIND_FILE_CHANGE\x10\x03\x12\x1a\n" +
	"\x16EVENT_KIND_SESSION_END\x10\x042R\n" +
	"\vShellEvents\x12C\n" +
	"\tSubscribe\x12\x19.koi.plugin.v1.ShellEvent\x1a\x17.koi.plugin.v1.Proposal(\x010\x01B:Z8github.com/blairham/koi-shell/pkg/pluginapi/v1;pluginapib\x06proto3"

var (
	file_koi_plugin_v1_events_proto_rawDescOnce sync.Once
	file_koi_plugin_v1_events_proto_rawDescData []byte
)

func file_koi_plugin_v1_events_proto_rawDescGZIP() []byte {
	file_koi_plugin_v1_events_proto_rawDescOnce.Do(func() {
		file_koi_plugin_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_koi_plugin_v1_events_proto_rawDesc), len(file_koi_plugin_v1_events_proto_rawDesc)))
	})
	return file_koi_plugin_v1_events_proto_rawDescData
}

var file_koi_plugin_v1_events_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_koi_plugin_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_koi_plugin_v1_events_proto_goTypes = []any{
	(EventKind)(0),     // 0: koi.plugin.v1.EventKind
	(*ShellEvent)(nil), // 1: koi.plugin.v1.ShellEvent
	(*Proposal)(nil),   // 2: koi.plugin.v1.Proposal
	nil,                // 3: koi.plugin.v1.ShellEvent.EnvEntry
}
var file_koi_plugin_v1_events_proto_depIdxs = []int32{
	0, // 0: koi.plugin.v1.ShellEvent.kind:type_name -> koi.plugin.v1.EventKind
	3, // 1: koi.plugin.v1.ShellEvent.env:type_name -> koi.plugin.v1.ShellEvent.EnvEntry
	1, // 2: koi.plugin.v1.ShellEvents.Subscribe:input_type -> koi.plugin.v1.ShellEvent
	2, // 3: koi.plugin.v1.ShellEvents.Subscribe:output_type -> koi.plugin.v1.Proposal
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_koi_plugin_v1_events_proto_init() }
func file_koi_plugin_v1_events_proto_init() {
	if File_koi_plugin_v1_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_koi_plugin_v1_events_proto_rawDesc), len(file_koi_plugin_v1_events_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_koi_plugin_v1_events_proto_goTypes,
		DependencyIndexes: file_koi_plugin_v1_events_proto_depIdxs,
		EnumInfos:         file_koi_plugin_v1_events_proto_enumTypes,
		MessageInfos:      file_koi_plugin_v1_events_proto_msgTypes,
	}.Build()
	File_koi_plugin_v1_events_proto = out.File
	file_koi_plugin_v1_events_proto_goTypes = nil
	file_koi_plugin_v1_events_proto_depIdxs = nil
}
