// ShellEvents — event-triggered automations (#83).
//
// The host streams session events to subscribed plugins, which may
// respond with *proposals*. The contract is defined here before any
// host wiring exists, which is the same order the rest of this package
// was built in: the shape of a plugin contract is much harder to change
// after plugins exist than before.
//
// **Status: contract only. The host does not serve this yet.** A plugin
// implementing it today will simply never be subscribed.
//
// Three rules, none of which are negotiable, and all of which are
// inherited rather than invented:
//
//   - **No exec channel, ever.** A plugin proposes; the shell decides.
//     This is the #111 line — gish hosts other people's agents rather
//     than being one — and it is why orchestration cannot move behind
//     the plugin boundary. Every proposal that leads to running
//     something goes through the same preview-and-approve surfaces as
//     #20 and #34: it lands in the editor buffer, or it is gated, and it
//     never runs on its own.
//   - **The host never blocks on a subscriber.** Events are
//     fire-and-forget into a bounded buffer, drop-oldest. A plugin that
//     stops reading loses events; it does not slow the prompt down. The
//     same deadline posture as every other call in this package.
//   - **Events carry allowlisted, scrub-safe data only.** A command name
//     and its exit status, not the full command line; the allowlisted
//     env subset, not the environment. The #10/#12/#20 posture applies
//     unchanged — an event stream is a new place for a secret to leak,
//     so it is designed not to carry one.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: gish/plugin/v1/events.proto

package pluginapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ShellEvents_Subscribe_FullMethodName = "/gish.plugin.v1.ShellEvents/Subscribe"
)

// ShellEventsClient is the client API for ShellEvents service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShellEventsClient interface {
	// Subscribe opens the event stream.
	//
	// Bidirectional on purpose. In go-plugin the *host* is the gRPC
	// client and the plugin is the server, so a host→plugin push needs
	// the host sending on a stream; and a plugin's proposal arrives
	// whenever it is ready rather than as a reply to one event, so the
	// return side is a stream too. A request/response RPC per event would
	// make the host wait on a plugin, which the second rule above forbids.
	Subscribe(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ShellEvent, Proposal], error)
}

type shellEventsClient struct {
	cc grpc.ClientConnInterface
}

func NewShellEventsClient(cc grpc.ClientConnInterface) ShellEventsClient {
	return &shellEventsClient{cc}
}

func (c *shellEventsClient) Subscribe(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ShellEvent, Proposal], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ShellEvents_ServiceDesc.Streams[0], ShellEvents_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ShellEvent, Proposal]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ShellEvents_SubscribeClient = grpc.BidiStreamingClient[ShellEvent, Proposal]

// ShellEventsServer is the server API for ShellEvents service.
// All implementations must embed UnimplementedShellEventsServer
// for forward compatibility.
type ShellEventsServer interface {
	// Subscribe opens the event stream.
	//
	// Bidirectional on purpose. In go-plugin the *host* is the gRPC
	// client and the plugin is the server, so a host→plugin push needs
	// the host sending on a stream; and a plugin's proposal arrives
	// whenever it is ready rather than as a reply to one event, so the
	// return side is a stream too. A request/response RPC per event would
	// make the host wait on a plugin, which the second rule above forbids.
	Subscribe(grpc.BidiStreamingServer[ShellEvent, Proposal]) error
	mustEmbedUnimplementedShellEventsServer()
}

// UnimplementedShellEventsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedShellEventsServer struct{}

func (UnimplementedShellEventsServer) Subscribe(grpc.BidiStreamingServer[ShellEvent, Proposal]) error {
	return status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedShellEventsServer) mustEmbedUnimplementedShellEventsServer() {}
func (UnimplementedShellEventsServer) testEmbeddedByValue()                     {}

// UnsafeShellEventsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShellEventsServer will
// result in compilation errors.
type UnsafeShellEventsServer interface {
	mustEmbedUnimplementedShellEventsServer()
}

func RegisterShellEventsServer(s grpc.ServiceRegistrar, srv ShellEventsServer) {
	// If the following call panics, it indicates UnimplementedShellEventsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ShellEvents_ServiceDesc, srv)
}

func _ShellEvents_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ShellEventsServer).Subscribe(&grpc.GenericServerStream[ShellEvent, Proposal]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ShellEvents_SubscribeServer = grpc.BidiStreamingServer[ShellEvent, Proposal]

// ShellEvents_ServiceDesc is the grpc.ServiceDesc for ShellEvents service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShellEvents_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gish.plugin.v1.ShellEvents",
	HandlerType: (*ShellEventsServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _ShellEvents_Subscribe_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "gish/plugin/v1/events.proto",
}
