// PromptSegmentProvider — async prompt segments (git status, k8s context,
// cloud account, …) from a resident plugin.
//
// The gitstatusd lesson, made a contract: prompt data is computed out of
// process and the prompt never blocks on it. The host calls Render with a
// deadline derived from the segment's declared budget; on a miss it
// renders the segment's previous (stale) value or nothing, and repaints
// in place when the response lands.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: gish/plugin/v1/prompt.proto

package pluginapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PromptSegmentProvider_Segments_FullMethodName = "/gish.plugin.v1.PromptSegmentProvider/Segments"
	PromptSegmentProvider_Render_FullMethodName   = "/gish.plugin.v1.PromptSegmentProvider/Render"
)

// PromptSegmentProviderClient is the client API for PromptSegmentProvider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PromptSegmentProviderClient interface {
	// Segments enumerates the segments this plugin offers. Called once
	// after Describe.
	Segments(ctx context.Context, in *SegmentsRequest, opts ...grpc.CallOption) (*SegmentsResponse, error)
	// Render produces the current text for one segment.
	Render(ctx context.Context, in *RenderRequest, opts ...grpc.CallOption) (*RenderResponse, error)
}

type promptSegmentProviderClient struct {
	cc grpc.ClientConnInterface
}

func NewPromptSegmentProviderClient(cc grpc.ClientConnInterface) PromptSegmentProviderClient {
	return &promptSegmentProviderClient{cc}
}

func (c *promptSegmentProviderClient) Segments(ctx context.Context, in *SegmentsRequest, opts ...grpc.CallOption) (*SegmentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SegmentsResponse)
	err := c.cc.Invoke(ctx, PromptSegmentProvider_Segments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promptSegmentProviderClient) Render(ctx context.Context, in *RenderRequest, opts ...grpc.CallOption) (*RenderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenderResponse)
	err := c.cc.Invoke(ctx, PromptSegmentProvider_Render_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PromptSegmentProviderServer is the server API for PromptSegmentProvider service.
// All implementations must embed UnimplementedPromptSegmentProviderServer
// for forward compatibility.
type PromptSegmentProviderServer interface {
	// Segments enumerates the segments this plugin offers. Called once
	// after Describe.
	Segments(context.Context, *SegmentsRequest) (*SegmentsResponse, error)
	// Render produces the current text for one segment.
	Render(context.Context, *RenderRequest) (*RenderResponse, error)
	mustEmbedUnimplementedPromptSegmentProviderServer()
}

// UnimplementedPromptSegmentProviderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPromptSegmentProviderServer struct{}

func (UnimplementedPromptSegmentProviderServer) Segments(context.Context, *SegmentsRequest) (*SegmentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Segments not implemented")
}
func (UnimplementedPromptSegmentProviderServer) Render(context.Context, *RenderRequest) (*RenderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Render not implemented")
}
func (UnimplementedPromptSegmentProviderServer) mustEmbedUnimplementedPromptSegmentProviderServer() {}
func (UnimplementedPromptSegmentProviderServer) testEmbeddedByValue()                               {}

// UnsafePromptSegmentProviderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PromptSegmentProviderServer will
// result in compilation errors.
type UnsafePromptSegmentProviderServer interface {
	mustEmbedUnimplementedPromptSegmentProviderServer()
}

func RegisterPromptSegmentProviderServer(s grpc.ServiceRegistrar, srv PromptSegmentProviderServer) {
	// If the following call panics, it indicates UnimplementedPromptSegmentProviderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PromptSegmentProvider_ServiceDesc, srv)
}

func _PromptSegmentProvider_Segments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SegmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromptSegmentProviderServer).Segments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PromptSegmentProvider_Segments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromptSegmentProviderServer).Segments(ctx, req.(*SegmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PromptSegmentProvider_Render_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromptSegmentProviderServer).Render(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PromptSegmentProvider_Render_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromptSegmentProviderServer).Render(ctx, req.(*RenderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PromptSegmentProvider_ServiceDesc is the grpc.ServiceDesc for PromptSegmentProvider service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PromptSegmentProvider_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gish.plugin.v1.PromptSegmentProvider",
	HandlerType: (*PromptSegmentProviderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Segments",
			Handler:    _PromptSegmentProvider_Segments_Handler,
		},
		{
			MethodName: "Render",
			Handler:    _PromptSegmentProvider_Render_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gish/plugin/v1/prompt.proto",
}
