// PromptSegmentProvider — async prompt segments (git status, k8s context,
// cloud account, …) from a resident plugin.
//
// The gitstatusd lesson, made a contract: prompt data is computed out of
// process and the prompt never blocks on it. The host calls Render with a
// deadline derived from the segment's declared budget; on a miss it
// renders the segment's previous (stale) value or nothing, and repaints
// in place when the response lands.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: koi/plugin/v1/prompt.proto

package pluginapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SegmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SegmentsRequest) Reset() {
	*x = SegmentsRequest{}
	mi := &file_koi_plugin_v1_prompt_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SegmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentsRequest) ProtoMessage() {}

func (x *SegmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_koi_plugin_v1_prompt_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentsRequest.ProtoReflect.Descriptor instead.
func (*SegmentsRequest) Descriptor() ([]byte, []int) {
	return file_koi_plugin_v1_prompt_proto_rawDescGZIP(), []int{0}
}

type SegmentDescriptor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Segment id, unique within the plugin (e.g. "git", "k8s-context").
	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Soft latency budget in milliseconds; the host derives Render
	// deadlines from it. 0 means "use the host default" (currently 50ms).
	BudgetMs uint32 `protobuf:"varint,3,opt,name=budget_ms,json=budgetMs,proto3" json:"budget_ms,omitempty"`
	// Environment variable names this segment wants per render (e.g.
	// AWS_PROFILE for an aws segment). The host filters the request
	// through its deny policy — secret-shaped names, loader hooks, and
	// shell internals are never sent, whatever a plugin declares.
	EnvKeys       []string `protobuf:"bytes,4,rep,name=env_keys,json=envKeys,proto3" json:"env_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SegmentDescriptor) Reset() {
	*x = SegmentDescriptor{}
	mi := &file_koi_plugin_v1_prompt_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SegmentDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentDescriptor) ProtoMessage() {}

func (x *SegmentDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_koi_plugin_v1_prompt_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentDescriptor.ProtoReflect.Descriptor instead.
func (*SegmentDescriptor) Descriptor() ([]byte, []int) {
	return file_koi_plugin_v1_prompt_proto_rawDescGZIP(), []int{1}
}

func (x *SegmentDescriptor) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SegmentDescriptor) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SegmentDescriptor) GetBudgetMs() uint32 {
	if x != nil {
		return x.BudgetMs
	}
	return 0
}

func (x *SegmentDescriptor) GetEnvKeys() []string {
	if x != nil {
		return x.EnvKeys
	}
	return nil
}

type SegmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Segments      []*SegmentDescriptor   `protobuf:"bytes,1,rep,name=segments,proto3" json:"segments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SegmentsResponse) Reset() {
	*x = SegmentsResponse{}
	mi := &file_koi_plugin_v1_prompt_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SegmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentsResponse) ProtoMessage() {}

func (x *SegmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_koi_plugin_v1_prompt_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentsResponse.ProtoReflect.Descriptor instead.
func (*SegmentsResponse) Descriptor() ([]byte, []int) {
	return file_koi_plugin_v1_prompt_proto_rawDescGZIP(), []int{2}
}

func (x *SegmentsResponse) GetSegments() []*SegmentDescriptor {
	if x != nil {
		return x.Segments
	}
	return nil
}

type RenderRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SegmentId string                 `protobuf:"bytes,1,opt,name=segment_id,json=segmentId,proto3" json:"segment_id,omitempty"`
	// Working directory the prompt is being drawn for.
	Cwd string `protobuf:"bytes,2,opt,name=cwd,proto3" json:"cwd,omitempty"`
	// Exit code of the last foreground pipeline.
	LastExitCode int32 `protobuf:"varint,3,opt,name=last_exit_code,json=lastExitCode,proto3" json:"last_exit_code,omitempty"`
	// Monotonic per-session sequence number; lets plugins drop stale
	// requests that were superseded before they were served.
	EventSeq uint64 `protobuf:"varint,4,opt,name=event_seq,json=eventSeq,proto3" json:"event_seq,omitempty"`
	// The values of the segment's declared env_keys that exist and pass
	// the host's deny policy.
	Env           map[string]string `protobuf:"bytes,5,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenderRequest) Reset() {
	*x = RenderRequest{}
	mi := &file_koi_plugin_v1_prompt_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderRequest) ProtoMessage() {}

func (x *RenderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_koi_plugin_v1_prompt_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderRequest.ProtoReflect.Descriptor instead.
func (*RenderRequest) Descriptor() ([]byte, []int) {
	return file_koi_plugin_v1_prompt_proto_rawDescGZIP(), []int{3}
}

func (x *RenderRequest) GetSegmentId() string {
	if x != nil {
		return x.SegmentId
	}
	return ""
}

func (x *RenderRequest) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *RenderRequest) GetLastExitCode() int32 {
	if x != nil {
		return x.LastExitCode
	}
	return 0
}

func (x *RenderRequest) GetEventSeq() uint64 {
	if x != nil {
		return x.EventSeq
	}
	return 0
}

func (x *RenderRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

type RenderResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Rendered segment text. Styling vocabulary is TBD (likely a small
	// markup subset, not raw ANSI) — raw text for now.
	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	// How long the host may reuse this value without re-rendering.
	TtlMs         uint32 `protobuf:"varint,2,opt,name=ttl_ms,json=ttlMs,proto3" json:"ttl_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenderResponse) Reset() {
	*x = RenderResponse{}
	mi := &file_koi_plugin_v1_prompt_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderResponse) ProtoMessage() {}

func (x *RenderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_koi_plugin_v1_prompt_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderResponse.ProtoReflect.Descriptor instead.
func (*RenderResponse) Descriptor() ([]byte, []int) {
	return file_koi_plugin_v1_prompt_proto_rawDescGZIP(), []int{4}
}

func (x *RenderResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *RenderResponse) GetTtlMs() uint32 {
	if x != nil {
		return x.TtlMs
	}
	return 0
}

var File_koi_plugin_v1_prompt_proto protoreflect.FileDescriptor

const file_koi_plugin_v1_prompt_proto_rawDesc = "" +
	"\n" +
	"\x1akoi/plugin/v1/prompt.proto\x12\rkoi.plugin.v1\"\x11\n" +
	"\x0fSegmentsRequest\"}\n" +
	"\x11SegmentDescriptor\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1b\n" +
	"\tbudget_ms\x18\x03 \x01(\rR\bbudgetMs\x12\x19\n" +
	"\benv_keys\x18\x04 \x03(\tR\aenvKeys\"P\n" +
	"\x10SegmentsResponse\x12<\n" +
	"\bsegments\x18\x01 \x03(\v2 .koi.plugin.v1.SegmentDescriptorR\bsegments\"\xf4\x01\n" +
	"\rRenderRequest\x12\x1d\n" +
	"\n" +
	"segment_id\x18\x01 \x01(\tR\tsegmentId\x12\x10\n" +
	"\x03cwd\x18\x02 \x01(\tR\x03cwd\x12$\n" +
	"\x0elast_exit_code\x18\x03 \x01(\x05R\flastExitCode\x12\x1b\n" +
	"\tevent_seq\x18\x04 \x01(\x04R\beventSeq\x127\n" +
	"\x03env\x18\x05 \x03(\v2%.koi.plugin.v1.RenderRequest.EnvEntryR\x03env\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\";\n" +
	"\x0eRenderResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x15\n" +
	"\x06ttl_ms\x18\x02 \x01(\rR\x05ttlMs2\xab\x01\n" +
	"\x15PromptSegmentProvider\x12K\n" +
	"\bSegments\x12\x1e.koi.plugin.v1.SegmentsRequest\x1a\x1f.koi.plugin.v1.SegmentsResponse\x12E\n" +
	"\x06Render\x12\x1c.koi.plugin.v1.RenderRequest\x1a\x1d.koi.plugin.v1.RenderResponseB:Z8github.com/blairham/koi-shell/pkg/pluginapi/v1;pluginapib\x06proto3"

var (
	file_koi_plugin_v1_prompt_proto_rawDescOnce sync.Once
	file_koi_plugin_v1_prompt_proto_rawDescData []byte
)

func file_koi_plugin_v1_prompt_proto_rawDescGZIP() []byte {
	file_koi_plugin_v1_prompt_proto_rawDescOnce.Do(func() {
		file_koi_plugin_v1_prompt_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_koi_plugin_v1_prompt_proto_rawDesc), len(file_koi_plugin_v1_prompt_proto_rawDesc)))
	})
	return file_koi_plugin_v1_prompt_proto_rawDescData
}

var file_koi_plugin_v1_prompt_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_koi_plugin_v1_prompt_proto_goTypes = []any{
	(*SegmentsRequest)(nil),   // 0: koi.plugin.v1.SegmentsRequest
	(*SegmentDescriptor)(nil), // 1: koi.plugin.v1.SegmentDescriptor
	(*SegmentsResponse)(nil),  // 2: koi.plugin.v1.SegmentsResponse
	(*RenderRequest)(nil),     // 3: koi.plugin.v1.RenderRequest
	(*RenderResponse)(nil),    // 4: koi.plugin.v1.RenderResponse
	nil,                       // 5: koi.plugin.v1.RenderRequest.EnvEntry
}
var file_koi_plugin_v1_prompt_proto_depIdxs = []int32{
	1, // 0: koi.plugin.v1.SegmentsResponse.segments:type_name -> koi.plugin.v1.SegmentDescriptor
	5, // 1: koi.plugin.v1.RenderRequest.env:type_name -> koi.plugin.v1.RenderRequest.EnvEntry
	0, // 2: koi.plugin.v1.PromptSegmentProvider.Segments:input_type -> koi.plugin.v1.SegmentsRequest
	3, // 3: koi.plugin.v1.PromptSegmentProvider.Render:input_type -> koi.plugin.v1.RenderRequest
	2, // 4: koi.plugin.v1.PromptSegmentProvider.Segments:output_type -> koi.plugin.v1.SegmentsResponse
	4, // 5: koi.plugin.v1.PromptSegmentProvider.Render:output_type -> koi.plugin.v1.RenderResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_koi_plugin_v1_prompt_proto_init() }
func file_koi_plugin_v1_prompt_proto_init() {
	if File_koi_plugin_v1_prompt_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_koi_plugin_v1_prompt_proto_rawDesc), len(file_koi_plugin_v1_prompt_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_koi_plugin_v1_prompt_proto_goTypes,
		DependencyIndexes: file_koi_plugin_v1_prompt_proto_depIdxs,
		MessageInfos:      file_koi_plugin_v1_prompt_proto_msgTypes,
	}.Build()
	File_koi_plugin_v1_prompt_proto = out.File
	file_koi_plugin_v1_prompt_proto_goTypes = nil
	file_koi_plugin_v1_prompt_proto_depIdxs = nil
}
