// ThemeProvider — whole-prompt themes from a resident plugin (#30).
//
// The third replacement tier for the prompt: where PromptSegmentProvider
// contributes one segment to the built-in layout, a ThemeProvider renders
// the *entire* prompt set (prompt, continuation, right prompt) per read.
// starship is the reference external implementation of this shape; this
// service is its native gRPC flavor.
//
// Contract: RenderPrompt is budget-bounded exactly like segments — the
// host derives a deadline from the theme's declared budget (default
// 50ms) and on a miss reuses the theme's previous prompt set or falls
// back to the built-in theme. The prompt never waits.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: koi/plugin/v1/theme.proto

package pluginapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ThemesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThemesRequest) Reset() {
	*x = ThemesRequest{}
	mi := &file_koi_plugin_v1_theme_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThemesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThemesRequest) ProtoMessage() {}

func (x *ThemesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_koi_plugin_v1_theme_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThemesRequest.ProtoReflect.Descriptor instead.
func (*ThemesRequest) Descriptor() ([]byte, []int) {
	return file_koi_plugin_v1_theme_proto_rawDescGZIP(), []int{0}
}

type ThemeDescriptor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Theme name, unique within the plugin (e.g. "tokyo-night"). Built-in
	// names (plain, p10k, starship) cannot be claimed; the built-ins win.
	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Soft latency budget in milliseconds; the host derives RenderPrompt
	// deadlines from it. 0 means "use the host default" (currently 50ms).
	BudgetMs      uint32 `protobuf:"varint,3,opt,name=budget_ms,json=budgetMs,proto3" json:"budget_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThemeDescriptor) Reset() {
	*x = ThemeDescriptor{}
	mi := &file_koi_plugin_v1_theme_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThemeDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThemeDescriptor) ProtoMessage() {}

func (x *ThemeDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_koi_plugin_v1_theme_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThemeDescriptor.ProtoReflect.Descriptor instead.
func (*ThemeDescriptor) Descriptor() ([]byte, []int) {
	return file_koi_plugin_v1_theme_proto_rawDescGZIP(), []int{1}
}

func (x *ThemeDescriptor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ThemeDescriptor) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ThemeDescriptor) GetBudgetMs() uint32 {
	if x != nil {
		return x.BudgetMs
	}
	return 0
}

type ThemesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Themes        []*ThemeDescriptor     `protobuf:"bytes,1,rep,name=themes,proto3" json:"themes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThemesResponse) Reset() {
	*x = ThemesResponse{}
	mi := &file_koi_plugin_v1_theme_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThemesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThemesResponse) ProtoMessage() {}

func (x *ThemesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_koi_plugin_v1_theme_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThemesResponse.ProtoReflect.Descriptor instead.
func (*ThemesResponse) Descriptor() ([]byte, []int) {
	return file_koi_plugin_v1_theme_proto_rawDescGZIP(), []int{2}
}

func (x *ThemesResponse) GetThemes() []*ThemeDescriptor {
	if x != nil {
		return x.Themes
	}
	return nil
}

// PromptContext is everything the shell knows at prompt time. Plugins
// must treat absent fields as unknown, not zero-meaningful.
type PromptContext struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Cwd   string                 `protobuf:"bytes,1,opt,name=cwd,proto3" json:"cwd,omitempty"`
	// The user's home directory, for ~ abbreviation.
	Home string `protobuf:"bytes,2,opt,name=home,proto3" json:"home,omitempty"`
	// Exit code of the last foreground pipeline.
	LastExitCode int32 `protobuf:"varint,3,opt,name=last_exit_code,json=lastExitCode,proto3" json:"last_exit_code,omitempty"`
	// Wall time of the last foreground pipeline.
	DurationMs uint64 `protobuf:"varint,4,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	// Filed jobs (running or stopped).
	Jobs     uint32 `protobuf:"varint,5,opt,name=jobs,proto3" json:"jobs,omitempty"`
	Username string `protobuf:"bytes,6,opt,name=username,proto3" json:"username,omitempty"`
	Hostname string `protobuf:"bytes,7,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// Whether the session arrived over SSH.
	Ssh bool `protobuf:"varint,8,opt,name=ssh,proto3" json:"ssh,omitempty"`
	// Terminal width in columns (0 = unknown).
	Width uint32 `protobuf:"varint,9,opt,name=width,proto3" json:"width,omitempty"`
	// Whether the terminal takes ANSI color. When false the response must
	// be plain text; the host degrades to the naked prompt otherwise.
	Color bool `protobuf:"varint,10,opt,name=color,proto3" json:"color,omitempty"`
	// Monotonic per-session sequence number; lets plugins drop stale
	// requests that were superseded before they were served.
	EventSeq      uint64 `protobuf:"varint,11,opt,name=event_seq,json=eventSeq,proto3" json:"event_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromptContext) Reset() {
	*x = PromptContext{}
	mi := &file_koi_plugin_v1_theme_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromptContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromptContext) ProtoMessage() {}

func (x *PromptContext) ProtoReflect() protoreflect.Message {
	mi := &file_koi_plugin_v1_theme_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromptContext.ProtoReflect.Descriptor instead.
func (*PromptContext) Descriptor() ([]byte, []int) {
	return file_koi_plugin_v1_theme_proto_rawDescGZIP(), []int{3}
}

func (x *PromptContext) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *PromptContext) GetHome() string {
	if x != nil {
		return x.Home
	}
	return ""
}

func (x *PromptContext) GetLastExitCode() int32 {
	if x != nil {
		return x.LastExitCode
	}
	return 0
}

func (x *PromptContext) GetDurationMs() uint64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *PromptContext) GetJobs() uint32 {
	if x != nil {
		return x.Jobs
	}
	return 0
}

func (x *PromptContext) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *PromptContext) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *PromptContext) GetSsh() bool {
	if x != nil {
		return x.Ssh
	}
	return false
}

func (x *PromptContext) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *PromptContext) GetColor() bool {
	if x != nil {
		return x.Color
	}
	return false
}

func (x *PromptContext) GetEventSeq() uint64 {
	if x != nil {
		return x.EventSeq
	}
	return 0
}

type RenderPromptRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Which of the plugin's themes to render (a plugin may serve several).
	Theme         string         `protobuf:"bytes,1,opt,name=theme,proto3" json:"theme,omitempty"`
	Context       *PromptContext `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenderPromptRequest) Reset() {
	*x = RenderPromptRequest{}
	mi := &file_koi_plugin_v1_theme_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderPromptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderPromptRequest) ProtoMessage() {}

func (x *RenderPromptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_koi_plugin_v1_theme_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderPromptRequest.ProtoReflect.Descriptor instead.
func (*RenderPromptRequest) Descriptor() ([]byte, []int) {
	return file_koi_plugin_v1_theme_proto_rawDescGZIP(), []int{4}
}

func (x *RenderPromptRequest) GetTheme() string {
	if x != nil {
		return x.Theme
	}
	return ""
}

func (x *RenderPromptRequest) GetContext() *PromptContext {
	if x != nil {
		return x.Context
	}
	return nil
}

type RenderPromptResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The first-line prompt; may span multiple lines (banner + edit line).
	Prompt string `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	// Continuation prompt for multi-line edits.
	ContPrompt string `protobuf:"bytes,2,opt,name=cont_prompt,json=contPrompt,proto3" json:"cont_prompt,omitempty"`
	// Right-side prompt for the first edit line; empty for none.
	Rprompt       string `protobuf:"bytes,3,opt,name=rprompt,proto3" json:"rprompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenderPromptResponse) Reset() {
	*x = RenderPromptResponse{}
	mi := &file_koi_plugin_v1_theme_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderPromptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderPromptResponse) ProtoMessage() {}

func (x *RenderPromptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_koi_plugin_v1_theme_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderPromptResponse.ProtoReflect.Descriptor instead.
func (*RenderPromptResponse) Descriptor() ([]byte, []int) {
	return file_koi_plugin_v1_theme_proto_rawDescGZIP(), []int{5}
}

func (x *RenderPromptResponse) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *RenderPromptResponse) GetContPrompt() string {
	if x != nil {
		return x.ContPrompt
	}
	return ""
}

func (x *RenderPromptResponse) GetRprompt() string {
	if x != nil {
		return x.Rprompt
	}
	return ""
}

var File_koi_plugin_v1_theme_proto protoreflect.FileDescriptor

const file_koi_plugin_v1_theme_proto_rawDesc = "" +
	"\n" +
	"\x19koi/plugin/v1/theme.proto\x12\rkoi.plugin.v1\"\x0f\n" +
	"\rThemesRequest\"d\n" +
	"\x0fThemeDescriptor\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1b\n" +
	"\tbudget_ms\x18\x03 \x01(\rR\bbudgetMs\"H\n" +
	"\x0eThemesResponse\x126\n" +
	"\x06themes\x18\x01 \x03(\v2\x1e.koi.plugin.v1.ThemeDescriptorR\x06themes\"\xa3\x02\n" +
	"\rPromptContext\x12\x10\n" +
	"\x03cwd\x18\x01 \x01(\tR\x03cwd\x12\x12\n" +
	"\x04home\x18\x02 \x01(\tR\x04home\x12$\n" +
	"\x0elast_exit_code\x18\x03 \x01(\x05R\flastExitCode\x12\x1f\n" +
	"\vduration_ms\x18\x04 \x01(\x04R\n" +
	"durationMs\x12\x12\n" +
	"\x04jobs\x18\x05 \x01(\rR\x04jobs\x12\x1a\n" +
	"\busername\x18\x06 \x01(\tR\busername\x12\x1a\n" +
	"\bhostname\x18\a \x01(\tR\bhostname\x12\x10\n" +
	"\x03ssh\x18\b \x01(\bR\x03ssh\x12\x14\n" +
	"\x05width\x18\t \x01(\rR\x05width\x12\x14\n" +
	"\x05color\x18\n" +
	" \x01(\bR\x05color\x12\x1b\n" +
	"\tevent_seq\x18\v \x01(\x04R\beventSeq\"c\n" +
	"\x13RenderPromptRequest\x12\x14\n" +
	"\x05theme\x18\x01 \x01(\tR\x05theme\x126\n" +
	"\acontext\x18\x02 \x01(\v2\x1c.koi.plugin.v1.PromptContextR\acontext\"i\n" +
	"\x14RenderPromptResponse\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12\x1f\n" +
	"\vcont_prompt\x18\x02 \x01(\tR\n" +
	"contPrompt\x12\x18\n" +
	"\arprompt\x18\x03 \x01(\tR\arprompt2\xaf\x01\n" +
	"\rThemeProvider\x12E\n" +
	"\x06Themes\x12\x1c.koi.plugin.v1.ThemesRequest\x1a\x1d.koi.plugin.v1.ThemesResponse\x12W\n" +
	"\fRenderPrompt\x12\".koi.plugin.v1.RenderPromptRequest\x1a#.koi.plugin.v1.RenderPromptResponseB:Z8github.com/blairham/koi-shell/pkg/pluginapi/v1;pluginapib\x06proto3"

var (
	file_koi_plugin_v1_theme_proto_rawDescOnce sync.Once
	file_koi_plugin_v1_theme_proto_rawDescData []byte
)

func file_koi_plugin_v1_theme_proto_rawDescGZIP() []byte {
	file_koi_plugin_v1_theme_proto_rawDescOnce.Do(func() {
		file_koi_plugin_v1_theme_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_koi_plugin_v1_theme_proto_rawDesc), len(file_koi_plugin_v1_theme_proto_rawDesc)))
	})
	return file_koi_plugin_v1_theme_proto_rawDescData
}

var file_koi_plugin_v1_theme_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_koi_plugin_v1_theme_proto_goTypes = []any{
	(*ThemesRequest)(nil),        // 0: koi.plugin.v1.ThemesRequest
	(*ThemeDescriptor)(nil),      // 1: koi.plugin.v1.ThemeDescriptor
	(*ThemesResponse)(nil),       // 2: koi.plugin.v1.ThemesResponse
	(*PromptContext)(nil),        // 3: koi.plugin.v1.PromptContext
	(*RenderPromptRequest)(nil),  // 4: koi.plugin.v1.RenderPromptRequest
	(*RenderPromptResponse)(nil), // 5: koi.plugin.v1.RenderPromptResponse
}
var file_koi_plugin_v1_theme_proto_depIdxs = []int32{
	1, // 0: koi.plugin.v1.ThemesResponse.themes:type_name -> koi.plugin.v1.ThemeDescriptor
	3, // 1: koi.plugin.v1.RenderPromptRequest.context:type_name -> koi.plugin.v1.PromptContext
	0, // 2: koi.plugin.v1.ThemeProvider.Themes:input_type -> koi.plugin.v1.ThemesRequest
	4, // 3: koi.plugin.v1.ThemeProvider.RenderPrompt:input_type -> koi.plugin.v1.RenderPromptRequest
	2, // 4: koi.plugin.v1.ThemeProvider.Themes:output_type -> koi.plugin.v1.ThemesResponse
	5, // 5: koi.plugin.v1.ThemeProvider.RenderPrompt:output_type -> koi.plugin.v1.RenderPromptResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_koi_plugin_v1_theme_proto_init() }
func file_koi_plugin_v1_theme_proto_init() {
	if File_koi_plugin_v1_theme_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_koi_plugin_v1_theme_proto_rawDesc), len(file_koi_plugin_v1_theme_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_koi_plugin_v1_theme_proto_goTypes,
		DependencyIndexes: file_koi_plugin_v1_theme_proto_depIdxs,
		MessageInfos:      file_koi_plugin_v1_theme_proto_msgTypes,
	}.Build()
	File_koi_plugin_v1_theme_proto = out.File
	file_koi_plugin_v1_theme_proto_goTypes = nil
	file_koi_plugin_v1_theme_proto_depIdxs = nil
}
