package promptengine

import (
	"os"
	"path/filepath"
	"slices"
	"strings"
	"testing"
)

// The fixture covers every syntactic form a real .p10k.zsh uses: the
// anonymous-function wrapper that defeats a bash parser, typeset flags,
// brace-expanded names, multi-line arrays with per-item comments, all
// three quoting styles, and an expansion that calls a shell function.
const zshFixture = `# Generated by Powerlevel10k configuration wizard.
'builtin' 'local' '-a' 'p10k_config_opts'
() {
  emulate -L zsh -o extended_glob

  typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
    dir                     # current directory
    vcs                     # git status
    newline                 # \n
    prompt_char             # prompt symbol
  )

  typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status time newline)

  typeset -g POWERLEVEL9K_MODE=nerdfont-v3
  typeset -g POWERLEVEL9K_ICON_PADDING=none
  typeset -g POWERLEVEL9K_{LEFT,RIGHT}_{LEFT,RIGHT}_WHITESPACE=
  typeset -g POWERLEVEL9K_{LEFT,RIGHT}_SUBSEGMENT_SEPARATOR=' '
  typeset -g POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=$''
  typeset -g POWERLEVEL9K_DIR_FOREGROUND=31
  typeset -g POWERLEVEL9K_TIME_FORMAT="%D{%H:%M:%S}"
  typeset -g POWERLEVEL9K_DIR_ANCHOR_BOLD=true
  typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX='%242F╭─'
  typeset -g POWERLEVEL9K_VCS_CONTENT_EXPANSION='${$((my_git_formatter(1)))+${my_git_format}}'
  typeset -g SOME_OTHER_VARIABLE=ignored

  function my_git_formatter() {
    emulate -L zsh -o extended_glob
    if [[ -n $P9K_CONTENT ]]; then
      typeset -g my_git_format=$P9K_CONTENT
      return
    fi
  }
}
`

func importFixture(t *testing.T) *Config {
	t.Helper()
	dir := t.TempDir()
	path := filepath.Join(dir, ".p10k.zsh")
	if err := os.WriteFile(path, []byte(zshFixture), 0o644); err != nil {
		t.Fatal(err)
	}
	cfg, err := ImportZshConfig(path)
	if err != nil {
		t.Fatal(err)
	}
	return cfg
}

func TestImportReadsElementLists(t *testing.T) {
	cfg := importFixture(t)

	want := []string{"dir", "vcs", "newline", "prompt_char"}
	if got := cfg.List("LEFT_PROMPT_ELEMENTS"); !slices.Equal(got, want) {
		t.Errorf("left elements = %v, want %v", got, want)
	}
	// The same list written on one line must read the same way.
	if got := cfg.List("RIGHT_PROMPT_ELEMENTS"); !slices.Equal(got, []string{"status", "time", "newline"}) {
		t.Errorf("right elements = %v", got)
	}
}

func TestImportExpandsBraceNames(t *testing.T) {
	cfg := importFixture(t)
	// One line sets four settings; losing this would lose the layout.
	for _, key := range []string{
		"LEFT_LEFT_WHITESPACE", "LEFT_RIGHT_WHITESPACE",
		"RIGHT_LEFT_WHITESPACE", "RIGHT_RIGHT_WHITESPACE",
	} {
		if !cfg.Has(key) {
			t.Errorf("%s was not set by the brace-expanded assignment", key)
		}
	}
	for _, key := range []string{"LEFT_SUBSEGMENT_SEPARATOR", "RIGHT_SUBSEGMENT_SEPARATOR"} {
		if got := cfg.Str(key, "<unset>"); got != " " {
			t.Errorf("%s = %q, want a space", key, got)
		}
	}
}

func TestImportHandlesQuotingStyles(t *testing.T) {
	cfg := importFixture(t)
	tests := []struct{ key, want string }{
		{"MODE", "nerdfont-v3"},                      // bare
		{"DIR_FOREGROUND", "31"},                     // bare numeric
		{"TIME_FORMAT", "%D{%H:%M:%S}"},              // double quoted
		{"MULTILINE_FIRST_PROMPT_PREFIX", "%242F╭─"}, // single quoted
		{"LEFT_SEGMENT_SEPARATOR", ""},              // $'...' escape
	}
	for _, tt := range tests {
		if got := cfg.Str(tt.key, "<unset>"); got != tt.want {
			t.Errorf("%s = %q, want %q", tt.key, got, tt.want)
		}
	}
}

func TestImportIgnoresForeignVariables(t *testing.T) {
	cfg := importFixture(t)
	if cfg.Has("SOME_OTHER_VARIABLE") {
		t.Error("import took a variable that is not ours")
	}
}

func TestImportReportsWhatItCannotTake(t *testing.T) {
	cfg := importFixture(t)
	// The stock config's git formatter is a shell function. It must be
	// named in the report, and must not be stored as if it were data.
	if cfg.Has("VCS_CONTENT_EXPANSION") {
		t.Error("an expansion calling a shell function was stored as a value")
	}
	found := slices.ContainsFunc(cfg.Unsupported, func(s string) bool {
		return strings.Contains(s, "VCS_CONTENT_EXPANSION")
	})
	if !found {
		t.Errorf("unsupported setting not reported: %v", cfg.Unsupported)
	}
}

func TestImportedConfigRenders(t *testing.T) {
	cfg := Preset("lean")
	cfg.Merge(importFixture(t))
	got := Render(cfg, sampleContext())
	if !strings.Contains(plain(got.Prompt), "gish") {
		t.Errorf("imported config did not render: %q", plain(got.Prompt))
	}
}
