package remote

import (
	"fmt"
	"os"
	"slices"
	"sort"
	"strings"
)

// The config bundle: the smallest thing that makes the remote shell feel
// like the local one.
//
// What travels is a generated rc file of KOI_* settings — theme, lint,
// tools, jump — and nothing else. Not history (it is the user's command
// record, and it belongs on their machine), not plugins (they do not
// travel in v1; the deadline-bounded degradation already makes their
// absence safe), and nothing resembling a credential.
//
// The bundle is pushed as a hash-named 0600 file next to the binary and
// named on the remote command line. Not as an argv blob, because argv is
// world-readable through /proc; not through SendEnv, because AcceptEnv
// restricts it server-side and silently drops what it does not allow.

// bundledVars are the settings worth carrying. The list is an allowlist
// on purpose: a "copy every KOI_* variable" rule would eventually carry
// something local-only (a socket path, a plugin dir) and produce a
// remote session that is subtly broken in a way nobody can debug.
var bundledVars = []string{
	"KOI_THEME",
	"KOI_THEME_SEGMENTS",
	"KOI_THEME_RPROMPT",
	"KOI_THEME_LINES",
	"KOI_THEME_FRAME",
	"KOI_THEME_SEP",
	"KOI_PROMPT",
	"KOI_PROMPT_CONT",
	"KOI_LINT",
	"KOI_TOOLS",
	"KOI_JUMP",
	"KOI_SEMANTIC_MARKS",
}

// Bundle renders the rc file to push. lookup supplies values (os.Getenv
// in production, a map in tests). Per-segment color overrides are picked
// up by prefix, since their names are open-ended.
func Bundle(lookup func(string) string, allNames []string) []byte {
	var b strings.Builder
	b.WriteString("# Generated by `koi ssh` — settings carried from the local session.\n")
	b.WriteString("# Nothing here is secret: no history, no credentials, no plugins.\n")

	names := slices.Clone(bundledVars)
	for _, n := range allNames {
		if strings.HasPrefix(n, "KOI_THEME_COLOR_") {
			names = append(names, n)
		}
	}
	sort.Strings(names)
	names = slices.Compact(names)

	for _, name := range names {
		v := lookup(name)
		if v == "" {
			continue
		}
		fmt.Fprintf(&b, "export %s=%s\n", name, shellQuote(v))
	}
	return []byte(b.String())
}

// EnvNames lists the current environment's variable names, for Bundle's
// prefix sweep.
func EnvNames() []string {
	env := os.Environ()
	out := make([]string, 0, len(env))
	for _, kv := range env {
		if name, _, ok := strings.Cut(kv, "="); ok {
			out = append(out, name)
		}
	}
	return out
}

// readmeText is dropped alongside the binary. This sounds like a
// nicety and is not: it is the difference between a sysadmin shrugging
// at an unfamiliar file and a sysadmin filing a "what is this binary on
// prod" ticket.
const readmeText = `This directory was created by koi (https://github.com/blairham/koi-shell),
a shell, when a user ran ` + "`koi ssh`" + ` to this host.

What is here:
  koi-<hash>    a statically linked koi binary, named by its own
                 sha256 so an upgrade is a new file, not an overwrite
  rc-<hash>      that user's prompt/theme settings, mode 0600
  README         this file

What it does NOT do:
  - it is not a daemon or an agent; nothing runs unless that user
    ssh's in and starts it
  - it did not modify any dotfile, shell configuration, or system
    setting, and it did not change anyone's login shell
  - it does not run as root and does not need to

To remove it: delete this directory. The user can also run
` + "`koi ssh --uninstall <host>`" + `, which does exactly that.
`
